(function(){
'use strict';
const {$}= { $:id=>document.getElementById(id)};
const {World,COWS,JOBS,BUILDINGS,QUESTS,SEAS,SHIPS,RESOURCE_NAMES}=CowWorld;
const KEY='crazy-cow-world-v1';let saved=null;try{saved=JSON.parse(localStorage.getItem(KEY));}catch{}
const world=new World(saved),renderer=new CowRenderer($('sea'),world);
let editing=false,editTool='expand',editSelection=null;
let panel=null,last=performance.now(),uiClock=0,saveClock=0,target=null,joy={x:0,y:0},keys=new Set(),pointer=null,previousFocus=null,storageFailed=false;
const paths={
 coin:'<circle cx="16" cy="16" r="11" fill="#e5b950" stroke="#ba903c"/><circle cx="16" cy="16" r="7" fill="none" stroke="#fff0ac"/><path d="M17 10h-3v5h4v6h-4m2-13v16" stroke="#ad8639" fill="none"/>',
 wood:'<path d="m5 10 17-4 6 7-4 12-18 2-3-7Z" fill="#bb9160"/><path d="m5 10 6 8 17-5M11 18l-5 9m5-9 13 7" fill="none" stroke="#846944"/><path d="m12 10 8-2m-7 5 10-2m-9 10 6 2" stroke="#e1bf8e"/>',
 grass:'<path d="M16 28C2 23 3 12 3 12c10 0 13 8 13 16Z" fill="#87a56a"/><path d="M16 28C10 14 15 3 19 2c4 11 1 18-3 26Z" fill="#668950"/><path d="M16 28c0-16 13-19 13-19-1 13-8 17-13 19Z" fill="#a5b975"/>',
 milk:'<path d="M11 3h10v5l3 5v15H8V13l3-5Z" fill="#d9dfd1" stroke="#8a9f91"/><path d="M11 3h10v4H11Z" fill="#77998b"/><path d="M9 15h14v9H9Z" fill="#fbf5df"/><path d="M16 16s-3 3-3 5a3 3 0 0 0 6 0c0-2-3-5-3-5Z" fill="#90b5ae"/>',
 feed:'<path d="m10 4 5 2 7-2-2 7c7 7 8 17 1 18H10c-7-1-6-11 2-18Z" fill="#c6b482"/><path d="M10 10h11m-6 6v9m-3-7 3 3 4-4m-7 4 3 3 4-4" fill="none" stroke="#8b855b"/>',
 build:'<path d="m6 24 15-17 5 5-16 16Z" fill="currentColor" opacity=".85"/><path d="m13 5 6-2 10 8-4 5-9-8-4 2-3-3Z" fill="currentColor"/><path d="m4 7 7 2-3 4 15 13-3 3L5 15l-3-4Z" fill="currentColor" opacity=".6"/>',
 cow:'<path d="M9 11 3 5l1 10 5 3m14-7 6-6-1 10-5 3M9 9h14l2 16-6 4h-7l-6-5Z" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M10 21h12v5H10Z" fill="currentColor" opacity=".2"/><path d="M11 15v3m10-3v3m-8 5v1m6-1v1" stroke="currentColor" stroke-width="2"/>',
 book:'<path d="M16 7C10 3 5 4 3 5v22c5-2 9-1 13 2 4-3 8-4 13-2V5c-4-1-8-1-13 2Zm0 0v22" fill="none" stroke="currentColor" stroke-width="1.7"/><path d="M7 10h5m-5 5h5m8-5h5m-5 5h5" stroke="currentColor" opacity=".6"/>',
 flag:'<path d="M7 29V4m1 1c8-5 10 6 18 1v14c-8 5-10-6-18-1" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="m13 11 3 3 5-5" fill="none" stroke="currentColor" stroke-width="1.6"/>',
 barn:'<path d="m3 14 13-11 13 11v15H3Z" fill="#a48158"/><path d="M0 14 16 0l16 14-3 2L16 5 3 16Z" fill="#c6b47d"/><path d="M11 18h10v11H11Z" fill="#665e46"/>',
 tea:'<path d="M7 10h19l-3 19H10Z" fill="#c7ae80"/><path d="M6 9h21v4H6Z" fill="#e7d9af"/><path d="m20 10 3-8h6" fill="none" stroke="#668c76" stroke-width="2"/><circle cx="13" cy="24" r="1.5" fill="#655f49"/><circle cx="18" cy="25" r="1.5" fill="#655f49"/><circle cx="21" cy="21" r="1.5" fill="#655f49"/>',
 net:'<path d="m5 5 22 0-11 21Z" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M9 5 19 20M14 5l8 10M20 5l5 5M25 5 12 20M19 5 9 15M13 5l-6 5M16 26v5" stroke="currentColor" stroke-width="1"/>',
 pause:'<path d="M10 7v18m12-18v18" stroke="currentColor" stroke-width="4" stroke-linecap="round"/>',
 sound:'<path d="M5 12h5l7-6v20l-7-6H5Z" fill="none" stroke="currentColor" stroke-width="2"/><path d="M22 10q8 6 0 12m3-16q12 10 0 20" fill="none" stroke="currentColor" stroke-width="1.6"/>',
 mute:'<path d="M5 12h5l7-6v20l-7-6H5Z" fill="none" stroke="currentColor" stroke-width="2"/><path d="m22 12 8 8m0-8-8 8" stroke="currentColor" stroke-width="2"/>',
 tile:'<path d="m2 11 15-8 13 8-15 10Z" fill="#c9ad77"/><path d="M2 11v7l13 10v-7m0 0 15-10v7L15 28" fill="#a58a5c"/><path d="m7 8 13 10M12 5l13 10" stroke="#8d7851"/>',
};
const icon=n=>`<svg viewBox="0 0 32 32" aria-hidden="true">${paths[n]||paths.cow}</svg>`;
for(const e of document.querySelectorAll('[data-icon]'))e.innerHTML=icon(e.dataset.icon);
$('salvageIcon').innerHTML=icon('net');$('pause').innerHTML=icon('pause');
$('resources').innerHTML=Object.keys(RESOURCE_NAMES).sort((a,b)=>['coin','grass','wood','milk','feed'].indexOf(a)-['coin','grass','wood','milk','feed'].indexOf(b)).map(k=>`<div class="resource" title="${RESOURCE_NAMES[k]}">${icon(k)}<span><small>${RESOURCE_NAMES[k]}</small><b id="res-${k}">0</b></span></div>`).join('');
// Original procedural music: a quiet pentatonic bell sequence, no audio files.
let audio=null,master=null,note=0,musicClock=0;
function audioStart(){try{if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=world.s.muted?0:.22;master.connect(audio.destination);}if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
function tone(freq,duration=.2,volume=.1,type='sine'){if(!audio||audio.state!=='running'||world.s.muted)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(0,audio.currentTime);g.gain.linearRampToValueAtTime(volume,audio.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g);g.connect(master);o.start();o.stop(audio.currentTime+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
function sfx(kind){if(kind==='rare'){[196,261.63,392,523.25].forEach((f,i)=>setTimeout(()=>tone(f,.6,.3,'triangle'),i*130));}else if(kind==='build'||kind==='reward'||kind==='rescue'){tone(523,.22,.3);setTimeout(()=>tone(784,.4,.25),90);}else tone(660,.1,.1);}
function music(dt){if(world.s.muted||!audio||audio.state!=='running')return;musicClock+=dt;if(musicClock>1.1){musicClock=0;const seq=[0,7,12,16,14,7,4,12,0,7,9,16,14,12,7,4];tone(130.81*2**(seq[note%seq.length]/12),1.8,.20);if(note%4===0)tone(65.4,3,.12,'triangle');note++;}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(world.s));$('saveState').textContent='本地自动存档';}catch{if(!storageFailed){toast('当前浏览器不能保存进度，本次仍可正常游玩。');storageFailed=true;}$('saveState').textContent='本次进度未保存';}}
function toast(text){const e=document.createElement('div');e.className='toast';e.textContent=text;$('toasts').appendChild(e);while($('toasts').children.length>3)$('toasts').firstChild.remove();setTimeout(()=>e.remove(),3600);}
function processNotices(){for(const n of world.notices.splice(0)){if(n.kind==='rare'){$('eventName').textContent=n.text+' · 正在靠近';$('event').classList.remove('show');void $('event').offsetWidth;$('event').classList.add('show');}else toast(n.text);sfx(n.kind);}}
function updateUI(){const s=world.s;for(const k in RESOURCE_NAMES)$('res-'+k).textContent=s.resources[k]>=100000?Math.floor(s.resources[k]/1000)+'k':Math.floor(s.resources[k]).toLocaleString();$('herdCount').textContent=`${world.herdSize} 头牛 · ${s.raftTier} 阶木筏`;$('tileCount').textContent=`${s.tiles.length} 块木筏`;$('level').textContent=`Lv. ${world.level}`;$('day').textContent='DAY '+String(1+Math.floor(s.time/120)).padStart(2,'0');$('islandName').textContent=world.shipStage.name;$('questTitle').textContent=world.task.name;const complete=world.taskProgress>=world.task.goal;$('questCount').textContent=complete?'领取 →':`${world.taskProgress}/${world.task.goal}`;$('questProgress').style.width=(world.taskProgress/world.task.goal*100)+'%';$('dockHerd').textContent=world.visibleWorkers.length+' 个工种';$('dockBook').textContent=s.discovered.length+' / 6 已发现';$('dockTask').textContent=complete?'奖励待领取':'成长日记';$('cooldown').textContent=s.cooldown>0?`${Math.ceil(s.cooldown)} 秒后可撒网`:'附近资源 · 自动收集';$('salvage').disabled=s.cooldown>0||s.paused;$('sound').innerHTML=icon(s.muted?'mute':'sound');$('sound').setAttribute('aria-label',s.muted?'开启声音':'关闭声音');$('sound').setAttribute('aria-pressed',String(s.muted));$('voyage').textContent=`第 ${s.sea} 海域 · ${world.canSail?'可远航':'远航 →'}`;$('voyage').classList.toggle('ready',world.canSail);$('weather').textContent=world.bonus>0?`✦ 丰收暖流 · ${Math.ceil(world.bonus)} 秒双倍打捞`:`☀ ${world.seaTheme.name} · 物资 ×${s.sea}`;}
function row(art,title,desc,cost,action,label,disabled=false){return `<div class="build-row"><div class="item-art">${icon(art)}</div><div class="item-details"><h3>${title}</h3><p>${desc}</p>${cost?`<p class="cost">${cost}</p>`:''}</div><button class="buy" data-action="${action}" ${disabled?'disabled':''}>${label}</button></div>`;}
function openPanel(name){if(editing)finishEditing();audioStart();previousFocus=document.activeElement;panel=name;target=null;keys.clear();joy={x:0,y:0};$('stick').style.transform='';$('modal').hidden=false;for(const e of $('game').children)if(e!==$('modal'))e.inert=true;renderPanel();$('close').focus();}
function closePanel(){if(world.s.paused){world.s.paused=false;save();}panel=null;$('modal').hidden=true;for(const e of $('game').children)e.inert=false;previousFocus?.focus();last=performance.now();}
function renderPanel(){const s=world.s,b=$('panelBody');const titles={build:['海上营造所','建设你的海上家园'],herd:['各司其职，一起把家建好','牛群 · 工种分配'],book:['海风会带来怎样的相遇','一本很牛的图鉴'],tasks:['把小日子，过成大梦想','小牛的成长日记'],pause:['慢一点，也没有关系','让海风等一等'],reset:['重新出发','开启一场新的梦'],voyage:['梦没有尽头，海也是','带着家园去远航']};$('panelEyebrow').textContent=titles[panel][0];$('panelTitle').textContent=titles[panel][1];
 if(panel==='build'){
  b.innerHTML=`<div class="ship-stages">${SHIPS.map(stage=>`<div class="ship-step ${world.shipStage.tier===stage.tier?'current':''} ${s.raftTier<stage.tier?'future':''}"><canvas data-ship="${stage.tier}" aria-label="${stage.name}船体预览"></canvas><strong>${stage.name}</strong><small>${stage.tier} 阶${world.shipStage.tier===stage.tier?' · 当前':''}</small></div>`).join('')}</div><p class="panel-intro">${world.shipStage.desc}<br>${world.nextShipStage?`下一次船型变化：${world.nextShipStage.tier} 阶 · ${world.nextShipStage.name}`:'方舟已成型，仍可持续升阶强化。'}<br>升阶后回到海面观看改造，自定义甲板轮廓会保留。</p>`
  +row('tile',`木筏升阶 <small>${s.raftTier} 阶 → ${s.raftTier+1} 阶</small>`,`产出 +15% 基础值 · 设施上限 ${world.buildingCap+2} 级 · 打捞范围提升`,world.costText(world.tierCost()),'tier','升阶',!world.canPay(world.tierCost()))
  +row('flag',`远航 · 第 ${s.sea} 海域`,`${world.seaTheme.name} · ${world.voyageGoals.filter(g=>g.value>=g.goal).length}/5 项准备就绪`,'保留木筏、牛群、设施与库存','voyage','查看')
  +row('tile','自定义船形',`新增 1 块空间 · 当前 ${s.tiles.length}/81 块`,`单格 ${world.costText(world.expandCost())} · 可拆除回收`,'edit','搭建')
  +row('grass','铺设青草',`每 3 块草地每轮产 1 青草 · 已铺 ${s.tiles.filter(t=>t.grass).length} 块`,'4 青草','plant','铺设',s.tiles.every(t=>t.grass)||s.resources.grass<4)
  +BUILDINGS.map(d=>{const lv=s.buildings[d.id]?.level||0,locked=world.level<d.unlock,capped=lv>=world.buildingCap;return row(d.icon,`${d.name} <small>${lv?'Lv.'+lv:'未建造'}</small>`,d.desc+' · 享受木筏产出加成',locked?`家园 Lv.${d.unlock} 解锁`:capped?'升阶木筏可继续升级':world.costText(world.buildingCost(d.id)),'build:'+d.id,locked?'未解锁':capped?'需升阶':lv?'升级':'选址',locked||capped||!world.canPay(world.buildingCost(d.id)));}).join('');requestAnimationFrame(()=>document.querySelectorAll('[data-ship]').forEach(c=>renderer.shipPortrait(c,Number(c.dataset.ship))));
 }
 if(panel==='voyage'){
  const next=SEAS[s.sea%SEAS.length];
  b.innerHTML=`<div class="voyage-summary"><span class="eyebrow">第 ${s.sea} 海域</span><h3>${world.seaTheme.name}</h3><p>${world.seaTheme.desc}</p><div class="voyage-metrics"><span>漂流收益 <b>×${s.sea}</b></span><span>来访牛品阶 <b>${s.sea} 阶</b></span><span>木筏产出 <b>+${Math.round((world.yieldBoost-1)*100)}%</b></span></div></div><p class="panel-intro">准备好就继续向前。远航保留全部建设、库存和伙伴，只更新海上漂流物与本海域目标。</p>`
  +world.voyageGoals.map(g=>`<div class="build-row"><span class="task-check">${g.value>=g.goal?'✓':'·'}</span><div class="item-details"><h3>${g.name}</h3></div><span class="badge">${Math.min(g.value,g.goal)} / ${g.goal}</span></div>`).join('')
  +`<div class="next-sea"><small>下一站 · 第 ${s.sea+1} 海域</small><h3>${next.name}</h3><p>漂流收益 ×${s.sea+1} · 牛品阶 ${s.sea+1} 阶</p></div><button class="buy wide" data-action="sail" ${world.canSail?'':'disabled'}>带上整个家，出发 →</button><button class="secondary" data-action="construction">去升阶 / 建造设施</button><p class="dev-note">四种海域风貌轮转，海域序号、木筏阶数与设施上限持续提升。</p>`;
 }

 if(panel==='book'){b.innerHTML='<p class="panel-intro">从初生的小牛到梦里的大家伙，每一次相遇都留在这里。提高家园等级解锁新牛种；远航遇到高品阶同类后，该牛种全体产出提升。</p><div class="book-grid">'+COWS.map((d,i)=>{const seen=s.discovered.includes(i);return `<div class="cow-card ${seen?'':'locked'}"><canvas data-cow="${i}"></canvas><h3>${seen?d.name:'未知的牛朋友'}</h3><p>${seen?d.desc:`家园 Lv.${d.level} 后出现`}</p><span class="badge">${seen?d.tag+' · '+s.breedRanks[i]+' 阶':'尚未相遇'}</span></div>`;}).join('')+'</div>';drawPortraits();}
 if(panel==='herd'){
  const teams=world.workerTeams,counts=world.workerCounts;
  b.innerHTML=`<div class="herd-summary"><div><b>${world.herdSize}</b><small>牛群总人数</small></div><div><b>${teams.filter(t=>t.count).length}</b><small>在岗工种</small></div><div><b>${Math.max(0,Math.ceil(world.productionInterval-s.production))}<small> 秒</small></b><small>下一轮生产</small></div></div><p class="panel-intro">每个工种只展示一头代表牛，其余成员照常工作。你操控的小牛是船长，单独显示；同种伙伴整队调岗，新救下的同种牛自动加入。</p>`;
  b.innerHTML+=teams.map(t=>`<div class="build-row"><div class="item-art">${icon(t.icon)}</div><div class="item-details"><h3>${t.name} <small>${t.count?'× '+t.count:'待分配'}</small></h3><p>${t.desc}${t.count?`<br>代表：${COWS[t.type].name}`:''}</p></div></div>`).join('');
  b.innerHTML+=`<h3 class="job-heading">小队调岗</h3><p class="panel-intro">产出受木筏、牛棚和品阶加成。建造员当前节省 ${Math.round(world.buildDiscount*100)}% 建造木材。</p>`;
  b.innerHTML+=counts.map((n,i)=>n?`<div class="job-assignment"><label for="job-${i}">${COWS[i].name}<small>${n} 头 · ${s.breedRanks[i]} 阶</small></label><select id="job-${i}" data-job-type="${i}" aria-label="${COWS[i].name}小队工种">${JOBS.map(j=>`<option value="${j.id}" ${s.jobs[i]===j.id?'selected':''}>${j.name}</option>`).join('')}</select></div>`:'').join('');
  if(!counts.some(Boolean))b.innerHTML+='<p class="panel-intro">先救下一位伙伴，就能为小队安排工种。</p>';
  b.innerHTML+='<p class="dev-note">甲板最多显示 6 头工种代表与 1 位船长。<br>牛群人数继续增长，每位成员只参与一个工种。</p>';
 }
 if(panel==='tasks'){b.innerHTML='<p class="panel-intro">完成任务后领取奖励。每个小小的进步，都在让海上牛王国长大。</p>'+QUESTS.map((q,i)=>{const past=i<s.quest,active=i===s.quest;return `<div class="build-row"><span class="task-check">${past?'✓':String(i+1).padStart(2,'0')}</span><div class="item-details"><h3>${q.name}</h3><p>${world.costText(q.reward)}</p></div>${past?'<span class="badge">已完成</span>':active?`<button class="buy gold" data-action="claim" ${world.taskProgress<q.goal?'disabled':''}>${world.taskProgress>=q.goal?'领取':world.taskProgress+' / '+q.goal}</button>`:'<span class="badge">待开启</span>'}</div>`;}).join('');b.innerHTML+=row('flag',`远航 · 第 ${s.sea} 海域`,world.seaTheme.name,'家园随行，海域持续推进','voyage','查看');if(s.quest>=QUESTS.length)b.innerHTML+=row('flag',world.task.name,'长期委托，可反复完成',world.costText(world.task.reward),'claim',world.taskProgress>=world.task.goal?'领取':'继续打捞',world.taskProgress<world.task.goal);}
 if(panel==='pause'){b.innerHTML=`<div class="pause-art">☁</div><p class="pause-copy">牛在休息，海也在休息。<br>你的海上家园已经保存，回来时我们继续。</p><button class="buy wide" data-action="resume">继续漂流 →</button><button class="secondary" data-action="sound">${s.muted?'开启':'关闭'}音乐与音效</button><div class="help">移动：拖动左下摇杆 / WASD / 方向键<br>打捞：靠近自动收集 / 点击海面移动 / 空格撒网<br>建设：扩建、铺草，再建造和升级生产设施<br>稀有牛：升级家园，留出位置迎接它们<br>暂停：Esc / P · 存档：当前浏览器本地保存</div><button class="secondary" data-action="reset">重新开始一场梦</button>`;}
 if(panel==='reset')b.innerHTML='<p class="pause-copy">这会清除当前浏览器里的木筏、牛群和资源进度。<br>确认后，从初生的小牛重新开始。</p><button class="buy wide" data-action="confirm-reset">确认重新开始</button><button class="secondary" data-action="cancel-reset">保留家园，返回</button>';
}
function drawPortraits(){requestAnimationFrame(()=>{document.querySelectorAll('[data-cow]').forEach(c=>renderer.portrait(c,Number(c.dataset.cow)));});}
function toggleSound(){audioStart();world.s.muted=!world.s.muted;if(master)master.gain.setTargetAtTime(world.s.muted?0:.22,audio.currentTime,.03);save();updateUI();}
$('panelBody').addEventListener('change',e=>{const el=e.target;if(el.dataset.jobType===undefined)return;if(world.assignJob(Number(el.dataset.jobType),el.value)){const scroll=$('panelBody').scrollTop;processNotices();save();updateUI();renderPanel();$('panelBody').scrollTop=scroll;$('job-'+el.dataset.jobType)?.focus({preventScroll:true});}});
$('panelBody').addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action;audioStart();if(a==='resume'){closePanel();return;}if(a==='sound'){toggleSound();renderPanel();return;}if(a==='reset'){panel='reset';renderPanel();return;}if(a==='cancel-reset'){panel='pause';renderPanel();return;}if(a==='confirm-reset'){world.s=CowWorld.fresh();world.drops=[];world.effects=[];world.bonus=0;world.spawnCount=0;for(let i=0;i<14;i++)world.spawnDrop(i%5);world.spawnCow(1,true);if(master)master.gain.setTargetAtTime(.22,audio.currentTime,.03);save();closePanel();toast('新的海风，新的开始。');updateUI();return;}if(a==='voyage'){panel='voyage';renderPanel();return;}if(a==='construction'){panel='build';renderPanel();return;}if(a==='sail'){if(world.sail()){save();closePanel();processNotices();updateUI();}return;}if(a==='edit'){startEditing('expand');return;}if(a==='tier'){if(world.upgradeRaft()){save();closePanel();processNotices();updateUI();}return;}if(a==='expand')world.expand();if(a==='plant')world.plant();if(a.startsWith('build:')){const id=a.split(':')[1];if(!world.s.buildings[id]){startEditing('place:'+id);return;}world.build(id);}if(a==='claim')world.claim();processNotices();save();updateUI();const scroll=$('panelBody').scrollTop;renderPanel();$('panelBody').scrollTop=scroll;$('close').focus({preventScroll:true});});
function finishEditing(){editing=false;renderer.editMode=null;renderer.selection=null;editSelection=null;$('buildEditor').hidden=true;$('game').classList.remove('is-building');target=null;last=performance.now();}
function startEditing(tool){closePanel();editing=true;editTool=tool;editSelection=null;renderer.editMode=tool;renderer.selection=null;keys.clear();releaseJoy();target=null;$('buildEditor').hidden=false;$('game').classList.add('is-building');updateEditor();}
function updateEditor(){
 const p=editSelection;let valid=false,cost={},label='确认搭建',hint='点击 + 空格预览，在下方确认后扣除木材。';
 if(editTool==='expand'){cost=world.expandCost();valid=!!p&&world.s.tiles.length<81&&world.expansionSites().some(t=>t.x===p.x&&t.z===p.z);}
 if(editTool==='grass'){cost={grass:4};label='确认种草';hint='选择一块尚未铺草的甲板。';valid=!!p&&!!world.tileAt(p.x,p.z)&&!world.tileAt(p.x,p.z).grass;}
 if(editTool==='remove'){label='确认拆除';hint='保留中央龙骨、设施与连通通路；至少保留 9 块甲板。';valid=!!p&&!world.removalProblem(p.x,p.z);if(p&&!valid)hint=world.removalProblem(p.x,p.z);}
 if(editTool.startsWith('place:')){const id=editTool.split(':')[1],d=BUILDINGS.find(b=>b.id===id);cost=world.buildingCost(id);label='确认建造';hint=`选择空闲甲板放置${d.name}。`;valid=!!p&&!!world.tileAt(p.x,p.z)&&!(p.x===0&&p.z===0)&&!Object.values(world.s.buildings).some(b=>b.x===p.x&&b.z===p.z);}
 $('buildHint').textContent=hint;
 $('buildSelection').textContent=p?`格子 ${p.x}, ${p.z} · ${editTool==='remove'?`回收 ${Math.floor((world.tileAt(p.x,p.z)?.cost||0)/2)} 木材`:world.costText(cost)}`:'先点击想搭建的位置';
 if(valid&&!world.canPay(cost))$('buildHint').textContent='物资不足，先完成搭建并回到海上打捞。';
 $('confirmBuild').textContent=label;$('confirmBuild').disabled=!valid||!world.canPay(cost);
 for(const b of document.querySelectorAll('[data-tool]'))b.classList.toggle('selected',b.dataset.tool===editTool);
}
for(const b of document.querySelectorAll('[data-tool]'))b.onclick=()=>{editTool=b.dataset.tool;renderer.editMode=editTool;updateEditor();};
$('finishBuild').onclick=finishEditing;
$('confirmBuild').onclick=()=>{
 if(!editing||!editSelection)return;const {x,z}=editSelection;let ok=false;
 if(editTool==='expand')ok=world.expand(x,z);
 if(editTool==='grass')ok=world.plant(x,z);
 if(editTool==='remove')ok=world.removeTile(x,z);
 if(editTool.startsWith('place:')){ok=world.build(editTool.split(':')[1],{x,z});if(ok)editTool='expand';}
 processNotices();save();updateUI();renderer.editMode=editTool;if(ok){editSelection=null;renderer.selection=null;}updateEditor();
};
for(const el of document.querySelectorAll('[data-panel]'))el.addEventListener('click',()=>openPanel(el.dataset.panel));
$('voyage').onclick=()=>openPanel('voyage');$('close').onclick=closePanel;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closePanel();});
$('sound').onclick=toggleSound;$('pause').onclick=()=>{world.s.paused=true;save();openPanel('pause');};
$('quest').onclick=()=>{if(world.taskProgress>=world.task.goal){world.claim();processNotices();save();updateUI();}else openPanel('tasks');};
$('salvage').onclick=()=>{audioStart();if(!panel&&!editing&&!world.s.paused){world.salvage();sfx('normal');processNotices();updateUI();}};
const j=$('joystick');function joyMove(e){const r=j.querySelector('.joy-ring').getBoundingClientRect();let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;const len=Math.hypot(x,y),max=r.width*.30;if(len>max){x=x/len*max;y=y/len*max;}joy={x:x/max,y:y/max};$('stick').style.transform=`translate(${x}px,${y}px)`;}
j.addEventListener('pointerdown',e=>{if(panel||editing||world.s.paused)return;audioStart();pointer=e.pointerId;j.setPointerCapture(pointer);target=null;joyMove(e);});j.addEventListener('pointermove',e=>{if(e.pointerId===pointer)joyMove(e);});function releaseJoy(){pointer=null;joy={x:0,y:0};$('stick').style.transform='';}j.addEventListener('pointerup',releaseJoy);j.addEventListener('pointercancel',releaseJoy);j.addEventListener('lostpointercapture',releaseJoy);
$('sea').addEventListener('pointerdown',e=>{if(panel||world.s.paused)return;audioStart();const rect=$('sea').getBoundingClientRect();const p=renderer.unproject(e.clientX-rect.left,e.clientY-rect.top+.08*renderer.scale);if(editing){editSelection={x:Math.round(p.x),z:Math.round(p.z)};renderer.selection=editSelection;updateEditor();return;}const cow=renderer.pickDeckCow(e.clientX-rect.left,e.clientY-rect.top);target=world.pathTo(cow?cow.x:p.x,cow?cow.z:p.z);const close=!cow&&world.drops.find(d=>{const q=renderer.project(d.x,.3,d.z);return Math.hypot(q[0]-e.clientX+rect.left,q[1]-e.clientY+rect.top)<32;});if(close)target=world.pathTo(close.x,close.z);});
window.addEventListener('keydown',e=>{if(e.key==='Tab'&&panel){const focusable=[...$('modal').querySelectorAll('button:not(:disabled)')];const first=focusable[0],end=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus();}return;}const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(e.repeat&&['p','escape',' '].includes(k))return;if(k==='escape'||k==='p'){if(editing){finishEditing();return;}if(panel)closePanel();else{world.s.paused=true;save();openPanel('pause');}return;}if(panel||editing)return;audioStart();if(k===' '){$('salvage').click();return;}keys.add(k);target=null;});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('blur',()=>{keys.clear();releaseJoy();target=null;save();});document.addEventListener('visibilitychange',()=>{keys.clear();releaseJoy();last=performance.now();if(document.hidden){save();audio?.suspend().catch(()=>{});}else if(!world.s.muted&&audio)audio.resume().catch(()=>{});});
window.addEventListener('pagehide',save);window.addEventListener('resize',()=>renderer.resize());document.addEventListener('contextmenu',e=>e.preventDefault());
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!panel&&!editing&&!world.s.paused&&!document.hidden){let sx=joy.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),sy=joy.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);let dx=sx+sy,dz=sy-sx;if(target?.length){renderer.moving=world.followPath(target,dt);if(!target.length)target=null;}
 else {const len=Math.hypot(dx,dz),before={...world.s.player};if(len>.04)world.move(dx/Math.max(1,len),dz/Math.max(1,len),dt);renderer.moving=Math.hypot(world.s.player.x-before.x,world.s.player.z-before.z)>1e-6;}
 world.update(dt);music(dt);processNotices();}else renderer.moving=false;renderer.destination=target?.length?target[target.length-1]:null;renderer.draw();uiClock+=dt;saveClock+=dt;if(uiClock>.2){uiClock=0;updateUI();}if(saveClock>5){saveClock=0;save();}requestAnimationFrame(frame);}
updateUI();processNotices();requestAnimationFrame(frame);if(world.s.paused)openPanel('pause');else if(!saved)setTimeout(()=>toast('小牛，欢迎来到海上。拖动摇杆，靠近漂流物吧！'),700);
})();
