import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { clone } from 'three/addons/utils/SkeletonUtils.js';
const FILES={dog:'dog.gltf',zombie:'thin-zombie.glb',pistol:'pistol.gltf',rifle:'rifle.gltf',shotgun:'shotgun.gltf',bat:'bat.gltf',pickup:'pickup.gltf',truck:'truck.gltf',barrel:'barrel.gltf',pallet:'pallet.gltf',trash:'trash.gltf',barrier:'barrier.gltf',couch:'couch.gltf',chest:'chest.gltf',pine:'Pine_1.gltf',deadTree:'DeadTree_1.gltf',bush:'Bush_Common.gltf',grass:'Grass_Common_Short.gltf',arms:'arms.glb'};
export class AssetLibrary {
 constructor(){this.models=new Map();}
 async load(progress){const leafTexture=await new THREE.TextureLoader().loadAsync('/models/Leaves.png');leafTexture.colorSpace=THREE.SRGBColorSpace;leafTexture.flipY=false;leafTexture.repeat.set(.18,.4);leafTexture.offset.set(.015,.02);const loader=new GLTFLoader();let loaded=0;await Promise.all(Object.entries(FILES).map(async([key,file])=>{const model=await loader.loadAsync('/models/'+file);const prepared=new Set();model.scene.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;const materials=Array.isArray(n.material)?n.material:[n.material];for(const mat of materials){if(prepared.has(mat))continue;prepared.add(mat);mat.roughness=Math.max(.65,mat.roughness??1);if(mat.transparent){mat.alphaTest=.4;mat.depthWrite=true;mat.transparent=false;}if(key==='bush'){mat.map=leafTexture;mat.alphaTest=.3;}if(['pine','bush','grass'].includes(key)){mat.side=THREE.DoubleSide;mat.color.multiply(new THREE.Color('#aeb798'));}if(['pickup','truck'].includes(key))mat.color.multiply(new THREE.Color('#afb09b'));}}});this.models.set(key,model);progress?.(++loaded,Object.keys(FILES).length);}));return this;}
 create(key,{height,length,rotation=Math.PI,animate=false}={}){const asset=this.models.get(key);if(!asset)throw Error('Missing model '+key);const root=new THREE.Group(),model=clone(asset.scene);root.add(model);model.rotation.y=rotation;model.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(model);const size=box.getSize(new THREE.Vector3());const factor=height?height/size.y:length?length/Math.max(size.x,size.z):1;model.scale.multiplyScalar(factor);model.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(model);const center=box.getCenter(new THREE.Vector3());model.position.x-=center.x;model.position.y-=box.min.y;model.position.z-=center.z;root.userData.assetKey=key;root.userData.model=model;if(animate&&asset.animations.length){root.userData.mixer=new THREE.AnimationMixer(model);root.userData.clips=asset.animations;this.play(root,'Idle');}return root;}
 play(root,name,{once=false,speed=1,restart=false,fade=.18}={}){const data=root.userData;if(!data.mixer||(data.clipName===name&&!restart))return;const clip=data.clips.find(c=>c.name===name)||data.clips.find(c=>c.name==='Idle');if(!clip)return;const next=data.mixer.clipAction(clip);next.reset().setEffectiveTimeScale(speed).setEffectiveWeight(1);next.setLoop(once?THREE.LoopOnce:THREE.LoopRepeat,once?1:Infinity);next.clampWhenFinished=once;if(data.action&&data.action!==next)data.action.fadeOut(fade);next.fadeIn(fade).play();data.action=next;data.clipName=name;}
}
