export const SAVE_KEY = 'huangcheng.save.v1';
export const ITEMS = {
 crowbar:{name:'旧缠线球棒',icon:'⚒',weight:1.6,kind:'weapon',slot:1,damage:30,range:2.8,rate:.65,rarity:'common'},
 pistol:{name:'9mm 手枪',icon:'⌁',weight:.85,kind:'weapon',slot:2,damage:38,range:70,rate:.32,ammo:'ammo9',mag:12,rarity:'uncommon'},
 shotgun:{name:'双管猎枪',icon:'⌁',weight:3.2,kind:'weapon',slot:3,damage:115,range:24,rate:.95,ammo:'shell',mag:2,rarity:'rare'},
 rifle:{name:'巡林步枪',icon:'⌁',weight:3.6,kind:'weapon',slot:4,damage:66,range:110,rate:.19,ammo:'ammo556',mag:24,rarity:'rare'},
 marksman:{name:'精密步枪',icon:'⌁',weight:4.1,kind:'weapon',slot:4,damage:95,range:150,rate:.55,ammo:'ammo556',mag:10,rarity:'epic'},
 ammo9:{name:'9mm 子弹',icon:'⁙',weight:.012,stack:30,rarity:'uncommon'},shell:{name:'猎枪弹',icon:'⁙',weight:.035,stack:15,rarity:'uncommon'},ammo556:{name:'步枪弹',icon:'⁙',weight:.015,stack:30,rarity:'uncommon'},
 canned:{name:'午餐肉罐头',icon:'▤',weight:.4,stack:4,kind:'food',hunger:38,rarity:'common'},bread:{name:'黑麦面包',icon:'◒',weight:.25,stack:4,kind:'food',hunger:26,rarity:'common'},meat:{name:'野兽生肉',icon:'◓',weight:.5,stack:4,kind:'food',hunger:30,risk:28,rarity:'common'},
 water:{name:'瓶装净水',icon:'♧',weight:.5,stack:4,kind:'drink',thirst:42,rarity:'common'},dirtywater:{name:'未经处理的水',icon:'♧',weight:.5,stack:4,kind:'drink',thirst:32,risk:35,rarity:'common'},
 bandage:{name:'消毒绷带',icon:'⊞',weight:.1,stack:5,kind:'medical',health:8,rarity:'common'},medkit:{name:'急救包',icon:'✚',weight:.6,stack:3,kind:'medical',health:48,rarity:'uncommon'},antibiotic:{name:'抗生素',icon:'✚',weight:.1,stack:5,kind:'medical',rarity:'rare'},
 dogfood:{name:'狗粮',icon:'♧',weight:.4,stack:5,kind:'dogfood',rarity:'common'},metal:{name:'金属零件',icon:'⚙',weight:.25,stack:10,rarity:'common'},cloth:{name:'布料',icon:'▧',weight:.1,stack:10,rarity:'common'},repair:{name:'武器清洁套装',icon:'⚒',weight:.5,stack:3,rarity:'uncommon'},fuel:{name:'燃料',icon:'▥',weight:1,stack:4,rarity:'uncommon'},battery:{name:'电池',icon:'▣',weight:.15,stack:5,kind:'battery',rarity:'uncommon'},backpack:{name:'旅行背包 · 24 格',icon:'▣',weight:.7,kind:'backpack',capacity:24,rarity:'rare'},milpack:{name:'军用背包 · 32 格',icon:'▣',weight:1,kind:'backpack',capacity:32,rarity:'epic'},armor:{name:'防护背心',icon:'♜',weight:2.5,kind:'armor',rarity:'rare'}
};
export const REGIONS = [
{id:'home',name:'旧加油站',x:0,z:44,r:16,danger:0,pool:'home'},
{id:'town',name:'松岭镇',x:-27,z:6,r:22,danger:2,pool:'house'},
{id:'market',name:'惠民超市',x:21,z:4,r:15,danger:3,pool:'food'},
{id:'clinic',name:'镇卫生所',x:-27,z:-24,r:14,danger:3,pool:'medical'},
{id:'police',name:'旧警察局',x:23,z:-33,r:17,danger:5,pool:'police'},
{id:'industrial',name:'北岸工业区',x:53,z:-64,r:22,danger:4,pool:'industrial'},
{id:'farm',name:'西郊农场',x:-63,z:42,r:22,danger:2,pool:'farm'},
{id:'forest',name:'松林与猎人营地',x:-68,z:-49,r:26,danger:2,pool:'forest'},
{id:'hospital',name:'县医院',x:-22,z:-78,r:23,danger:8,pool:'hospital'}
];
const POOLS={house:['canned','bread','water','cloth','bandage','battery','dogfood','backpack'],food:['canned','canned','water','water','bread','dogfood','dogfood','dirtywater'],medical:['bandage','bandage','medkit','antibiotic','water','cloth'],police:['ammo9','ammo9','pistol','shell','ammo556','armor','rifle','marksman'],industrial:['metal','metal','cloth','repair','fuel','battery'],farm:['bread','canned','dogfood','shell','shotgun','cloth','dirtywater'],forest:['water','canned','shell','shotgun','bandage','backpack'],hospital:['bandage','medkit','medkit','antibiotic','armor','milpack']};
let sequence=0;
export function item(type,qty=1){const d=ITEMS[type];return {id:`i${Date.now().toString(36)}-${++sequence}`,type,qty,...(d.kind==='weapon'||d.kind==='armor'?{durability:100}:{}),...(d.mag?{loaded:0}:{})};}
export function weight(bag){return bag.reduce((n,i)=>n+ITEMS[i.type].weight*i.qty,0);}
export function addTo(bag,entry,capacity){const limit=ITEMS[entry.type].stack||1;let remaining=entry.qty;const room=bag.filter(i=>i.type===entry.type&&limit>1).reduce((n,i)=>n+limit-i.qty,0)+(capacity-bag.length)*limit;if(room<remaining)return false;for(const i of bag){if(i.type===entry.type&&limit>1){const n=Math.min(remaining,limit-i.qty);i.qty+=n;remaining-=n;if(!remaining)return true;}}while(remaining){const n=Math.min(remaining,limit);bag.push({...entry,id:remaining===entry.qty?entry.id:item(entry.type).id,qty:n});remaining-=n;}return true;}
export function count(bag,type){return bag.filter(i=>i.type===type).reduce((n,i)=>n+i.qty,0);}
export function consume(bag,type,qty=1){if(count(bag,type)<qty)return false;for(let i=bag.length-1;i>=0&&qty;i--){if(bag[i].type!==type)continue;const n=Math.min(qty,bag[i].qty);bag[i].qty-=n;qty-=n;if(!bag[i].qty)bag.splice(i,1);}return true;}
export function freshState(){const crowbar=item('crowbar');return {version:1,time:0,dayTime:8.3,deaths:0,position:{x:0,z:37},yaw:0,pitch:0,health:100,hunger:87,thirst:86,stamina:100,infection:0,bleeding:false,temperature:37,bag:[crowbar,item('water'),item('canned'),item('bandage'),item('dogfood')],equipped:crowbar.id,capacity:16,armor:null,safe:[item('pistol'),item('ammo9',18)],safeCapacity:20,storage:[],crates:{},corpses:[],dog:{health:100,hunger:85},flashlight:100,weather:'阴天',nextWeather:210,nextEvent:100,dead:false};}
export function validateSave(s){if(!s||s.version!==1)throw Error('不支持的存档版本');const validBag=(b,cap)=>Array.isArray(b)&&b.length<=cap&&b.every(i=>i&&ITEMS[i.type]&&typeof i.id==='string'&&Number.isInteger(i.qty)&&i.qty>0&&i.qty<=(ITEMS[i.type].stack||1)&&(!(ITEMS[i.type].kind==='weapon'||ITEMS[i.type].kind==='armor')||(Number.isFinite(i.durability)&&i.durability>=0&&i.durability<=100))&&(!ITEMS[i.type].mag||(Number.isInteger(i.loaded)&&i.loaded>=0&&i.loaded<=ITEMS[i.type].mag)));if(![16,24,32].includes(s.capacity)||![20,40,60,100].includes(s.safeCapacity)||!validBag(s.bag,s.capacity)||!validBag(s.safe,s.safeCapacity)||!validBag(s.storage,30))throw Error('存档物品数据损坏');for(const k of ['health','hunger','thirst','stamina','infection','flashlight'])if(!Number.isFinite(s[k])||s[k]<0||s[k]>100)throw Error('存档状态损坏');if(!s.position||!Number.isFinite(s.position.x)||!Number.isFinite(s.position.z)||Math.abs(s.position.x)>115||Math.abs(s.position.z)>115||!Number.isFinite(s.time)||s.time<0||!Number.isFinite(s.dayTime)||!Number.isFinite(s.yaw)||!Number.isFinite(s.pitch)||!s.dog||!Number.isFinite(s.dog.health)||!Number.isFinite(s.dog.hunger))throw Error('存档坐标或时间损坏');if(!s.crates||typeof s.crates!=='object'||!Array.isArray(s.corpses)||s.corpses.length>100)throw Error('存档世界数据损坏');for(const c of [...Object.values(s.crates),...s.corpses])if(!validBag(c.items,100)||!Number.isFinite(c.x)||!Number.isFinite(c.z))throw Error('存档容器损坏');if(!['晴天','阴天','小雨','暴雨','雾'].includes(s.weather)||!Number.isFinite(s.nextWeather)||!Number.isFinite(s.nextEvent)||!Number.isFinite(s.temperature)||s.temperature<30||s.temperature>42||s.dayTime<0||s.dayTime>=24||!Number.isInteger(s.deaths)||s.deaths<0||typeof s.dead!=='boolean'||typeof s.bleeding!=='boolean'||s.dog.health<0||s.dog.health>100||s.dog.hunger<0||s.dog.hunger>100)throw Error('存档环境状态损坏');if(s.armor&&(!validBag([s.armor],1)||s.armor.type!=='armor'))throw Error('存档护甲损坏');for(const c of s.corpses)if(typeof c.id!=='string'||!Number.isFinite(c.expires))throw Error('尸体存档损坏');for(const c of Object.values(s.crates))if(!POOLS[c.pool]||!Number.isFinite(c.visited)||!Number.isFinite(c.refreshAt))throw Error('资源存档损坏');return s;}
export class Survival {
 constructor(state=freshState(),rng=Math.random){this.s=state;this.rng=rng;this.messages=[];this.lastShot=-10;this.reloadAt=0;this.reloadingId=null;}
 notify(text){this.messages.push(text);}
 get weapon(){return this.s.bag.find(i=>i.id===this.s.equipped&&ITEMS[i.type].kind==='weapon');}
 get inHome(){return Math.hypot(this.s.position.x,this.s.position.z-44)<16;}
 get region(){return REGIONS.find(r=>Math.hypot(this.s.position.x-r.x,this.s.position.z-r.z)<r.r)||{name:'松岭郊野',danger:1};}
 equip(slot){const w=this.s.bag.find(i=>ITEMS[i.type].slot===slot);if(!w){this.notify('背包里没有这类武器');return;}this.s.equipped=w.id;this.reloadAt=0;}
 use(id){const s=this.s,i=s.bag.find(i=>i.id===id);if(!i)return;const d=ITEMS[i.type];if(d.kind==='weapon'){s.equipped=i.id;this.reloadAt=0;return;}if(d.kind==='food'){s.hunger=Math.min(100,s.hunger+d.hunger);if(d.risk&&this.rng()<.35)s.infection=Math.min(100,s.infection+d.risk);}else if(d.kind==='drink'){s.thirst=Math.min(100,s.thirst+d.thirst);if(d.risk&&this.rng()<.5)s.infection=Math.min(100,s.infection+d.risk);}else if(d.kind==='medical'){if(i.type==='antibiotic')s.infection=0;else{s.health=Math.min(100,s.health+(d.health||0));s.bleeding=false;}}else if(d.kind==='dogfood'){s.dog.hunger=Math.min(100,s.dog.hunger+45);this.notify('阿灰低下头，尾巴轻轻摇了起来。');}else if(d.kind==='battery')s.flashlight=Math.min(100,s.flashlight+70);else if(d.kind==='backpack'){if(s.capacity>=d.capacity){this.notify('已经有同等或更大的背包');return;}s.capacity=d.capacity;}else if(d.kind==='armor'){const previous=s.armor;s.armor={...i};const index=s.bag.indexOf(i);if(previous)s.bag[index]=previous;else s.bag.splice(index,1);return;}else{this.notify('在据点工作台使用这份材料');return;}i.qty--;if(!i.qty)s.bag.splice(s.bag.indexOf(i),1);}
 transfer(from,to,id,cap){const i=from.find(i=>i.id===id);if(!i)return false;if(!addTo(to,{...i},cap)){this.notify('空间不足，先腾出一些位置');return false;}from.splice(from.indexOf(i),1);if(!this.weapon)this.s.equipped=this.s.bag.find(i=>ITEMS[i.type].kind==='weapon')?.id||null;return true;}
 generateLoot(pool){const entries=[];if(this.rng()<.15)return entries;const n=1+Math.floor(this.rng()*4),types=POOLS[pool]||POOLS.house;for(let j=0;j<n;j++){const type=types[Math.floor(this.rng()*types.length)],d=ITEMS[type];if(d.rarity==='epic'&&this.rng()>.045)continue;if(d.rarity==='rare'&&this.rng()>.3)continue;const qty=d.ammo?1:type.startsWith('ammo')?3+Math.floor(this.rng()*9):type==='shell'?2+Math.floor(this.rng()*4):type==='metal'||type==='cloth'?2+Math.floor(this.rng()*3):1;addTo(entries,item(type,qty),10);}return entries;}
 crate(id,pool,x,z){return this.s.crates[id]??=( {id,pool,x,z,items:this.generateLoot(pool),visited:this.s.time,refreshAt:this.s.time+300});}
 refreshCrates(){const s=this.s;for(const c of Object.values(s.crates)){const near=Math.hypot(c.x-s.position.x,c.z-s.position.z)<35;if(near)c.visited=s.time;else if(s.time-c.visited>=300&&s.time>=c.refreshAt){if(this.rng()<.7)c.items=this.generateLoot(c.pool);c.refreshAt=s.time+180;c.visited=s.time;}}s.corpses=s.corpses.filter(c=>c.expires>s.time);}
 reload(){const w=this.weapon;if(!w||!ITEMS[w.type].mag||this.reloadAt)return;const d=ITEMS[w.type];if(w.loaded===d.mag)return;if(!count(this.s.bag,d.ammo)){this.notify('没有对应的弹药');return;}this.reloadAt=this.s.time+(w.type==='shotgun'?2.5:1.6);this.reloadingId=w.id;this.notify('换弹中…');}
 fire(){const w=this.weapon;if(!w){this.notify('没有装备武器');return null;}const d=ITEMS[w.type];if(this.reloadAt||this.s.time-this.lastShot<d.rate)return null;if(w.durability<=0){this.notify('武器已损坏，需要修理');return null;}if(d.ammo&&w.loaded<=0){this.notify('弹匣空了 · R 换弹');return null;}this.lastShot=this.s.time;if(d.ammo)w.loaded--;w.durability=Math.max(0,w.durability-(d.ammo?.34:.5));return d;}
 damage(n,{bleed=false,infect=false}={}){const s=this.s;if(s.dead)return;if(s.armor?.durability>0){s.armor.durability=Math.max(0,s.armor.durability-n*.7);n*=.6;}s.health=Math.max(0,s.health-n);if(bleed)s.bleeding=true;if(infect)s.infection=Math.min(100,s.infection+12);if(s.health<=0)this.die();}
 die(){const s=this.s;if(s.dead)return;s.dead=true;s.deaths++;const all=s.bag.map(i=>({...i}));if(s.armor)all.push({...s.armor});if(s.capacity>16)all.push(item(s.capacity===32?'milpack':'backpack'));for(const i of all)if(i.durability!==undefined)i.durability=Math.max(0,i.durability-15);s.corpses.push({id:`body-${s.time}`,x:s.position.x,z:s.position.z,items:all,expires:s.time+900});s.bag=[];s.armor=null;s.equipped=null;s.capacity=16;this.reloadAt=0;}
 respawn(){const s=this.s,spawns=[{x:-8,z:61},{x:-44,z:63},{x:30,z:51},{x:-53,z:14}];s.position={...spawns[Math.floor(this.rng()*spawns.length)]};s.bag=[item('crowbar'),item('water'),item('bread')];s.equipped=s.bag[0].id;Object.assign(s,{health:100,hunger:72,thirst:75,stamina:100,infection:0,bleeding:false,temperature:37,dead:false,flashlight:35,yaw:0,pitch:0});s.dog.health=Math.max(35,s.dog.health);this.notify('阿灰从远处跑来。你们又有了一次机会。');}
 repair(){const w=this.weapon;if(!this.inHome||!w)return;if(consume(this.s.bag,'repair'))w.durability=100;else if(count(this.s.bag,'metal')>=2&&count(this.s.bag,'cloth')>=1){consume(this.s.bag,'metal',2);consume(this.s.bag,'cloth');w.durability=Math.min(100,w.durability+45);}else{this.notify('需要清洁套装，或 2 金属零件 + 1 布料');return;}this.notify('武器已经修理');}
 upgrade(){const s=this.s;if(!this.inHome)return;const next={20:40,40:60,60:100}[s.safeCapacity];if(!next){this.notify('保险柜已达到最大容量');return;}const cost=s.safeCapacity/2;if(count(s.bag,'metal')<cost||count(s.bag,'cloth')<5){this.notify(`升级需要 ${cost} 金属零件 + 5 布料（放在背包中）`);return;}consume(s.bag,'metal',cost);consume(s.bag,'cloth',5);s.safeCapacity=next;this.notify(`保险柜扩展到 ${next} 格`);}
 tick(dt,{sprinting=false,moving=false,flashlight=false}={}){const s=this.s;if(s.dead)return;s.time+=dt;s.dayTime=(s.dayTime+dt/100)%24;s.hunger=Math.max(0,s.hunger-dt*.025);s.thirst=Math.max(0,s.thirst-dt*(sprinting?.06:.038));s.dog.hunger=Math.max(0,s.dog.hunger-dt*.023);s.stamina=Math.max(0,Math.min(100,s.stamina+dt*(sprinting&&moving?-(12+weight(s.bag)*.55):(s.infection>0?6:10))));if(flashlight)s.flashlight=Math.max(0,s.flashlight-dt*.065);const wet=['小雨','暴雨'].includes(s.weather)&&!this.inHome;s.temperature=Math.max(34,Math.min(37,s.temperature+dt*(wet?-.004:.009)));if(s.temperature<35.2)s.infection=Math.min(100,s.infection+dt*.01);const hurt=(s.hunger<=0?.1:0)+(s.thirst<=0?.22:0)+(s.bleeding?.35:0)+(s.infection>0?s.infection*.0015:0);if(hurt)this.damage(dt*hurt);else if(s.hunger>60&&s.thirst>60)s.health=Math.min(100,s.health+dt*.015);if(s.dog.hunger<10)s.dog.health=Math.max(10,s.dog.health-dt*.03);if(this.inHome)s.dog.health=Math.min(100,s.dog.health+dt*1.2);if(this.reloadAt&&s.time>=this.reloadAt){const w=this.weapon;if(w&&w.id===this.reloadingId){const d=ITEMS[w.type],n=Math.min(d.mag-w.loaded,count(s.bag,d.ammo));consume(s.bag,d.ammo,n);w.loaded+=n;}this.reloadAt=0;}if(s.time>=s.nextWeather){s.weather=['晴天','阴天','小雨','暴雨','雾'][Math.floor(this.rng()*5)];s.nextWeather=s.time+180+this.rng()*220;this.notify(`天色变了。${s.weather==='晴天'?'阳光穿过云隙。':s.weather+'笼罩了松岭。'}`);}if(Math.floor(s.time)!==Math.floor(s.time-dt)&&Math.floor(s.time)%10===0)this.refreshCrates();}
}
