import './style.css';
import * as THREE from 'three';
import {Survival,ITEMS,REGIONS,SAVE_KEY,freshState,validateSave,weight,count,consume,item,addTo} from './core.js';
import {World} from './world.js';
import {AssetLibrary} from './assets.js';
import {Soundscape} from './audio.js';
const $=id=>document.getElementById(id);
let saveWarning='';let state;
try{const raw=localStorage.getItem(SAVE_KEY);if(raw)state=validateSave(JSON.parse(raw));}catch(e){saveWarning='旧存档无法读取；已开启新旅程，旧数据不会立即覆盖。';}
const game=new Survival(state||freshState());const sound=new Soundscape();let world;
try{$('start').disabled=true;const assets=await new AssetLibrary().load((n,total)=>{$('start').textContent=`加载模型 ${n} / ${total}`;});world=new World($('world'),assets);$('start').innerHTML='进入荒城 <span>↗</span>';$('start').disabled=false;}catch(e){$('title-screen').innerHTML='<h1>荒城</h1><p>无法启动 3D 画面。请使用支持 WebGL 2 的桌面浏览器，并开启硬件加速。</p>';throw e;}
let started=false,locked=false,panel=null,context=null,aim=false,flashlight=false,recoil=0,jump=0,jumpV=0,noticeUntil=0,lastSave=0,lastHealth=game.s.health,deathShown=false,searchUntil=0,searchCooldown=0,dogTarget=null,dogMode='跟着你',dogLastAttack=0,dogLastBark=-30,stepAt=0,eventUntil=0,lastHUD=0,lastClock=performance.now(),saveBlocked=!!saveWarning;
const keys=new Set();const ray=new THREE.Raycaster();const v2=new THREE.Vector2(0,0);
if(state)$('save-label').textContent=`继续本地存档 · 第 ${Math.floor(state.time/2400)+1} 天 · 重生 ${state.deaths} 次`;
for(const r of REGIONS){for(let i=0;i<r.danger;i++){const a=i*2.39,x=r.x+Math.sin(a)*(r.r*.65),z=r.z+Math.cos(a)*(r.r*.65);if(!world.collides(x,z,.4))world.makeEnemy(x,z);}}
world.makeEnemy(-83,24,true);world.makeEnemy(-91,-17,true);world.syncCorpses(game.s.corpses);
function notify(text){$('notice').textContent=text;noticeUntil=performance.now()+4800;}
function save(){if(saveBlocked)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(game.s));$('save-status').textContent='本地存档 · 已保存';lastSave=game.s.time;}catch{$('save-status').textContent='存储失败 · 请导出存档';}}
function release(){keys.clear();aim=false;document.exitPointerLock?.();}
async function lock(){if(!started||game.s.dead)return;panel=null;for(const id of ['inventory','map-panel','pause'])$(id).hidden=true;try{await $('world').requestPointerLock();locked=document.pointerLockElement===$('world');}catch{notify('点击画面继续；若鼠标无法锁定，请允许浏览器捕获鼠标。');$('pause').hidden=false;panel='pause';}}
function showPanel(type,c=null){panel=type;context=c;release();for(const id of ['inventory','map-panel','pause'])$(id).hidden=id!==type;if(type==='inventory')renderInventory();if(type==='map-panel')drawMap();save();}
function closePanel(){lock();}
$('start').onclick=()=>{started=true;sound.start();$('title-screen').hidden=true;$('scene-caption').hidden=true;$('hud').hidden=false;saveBlocked=false;if(game.s.dead){showDeath();return;}lock();notify(saveWarning||'旧加油站是你的据点。保险柜在站房内，入口在南侧。');world.dog.position.set(game.s.position.x+2,0,game.s.position.z+1);};
$('resume').onclick=()=>{sound.start();lock();};$('help-button').onclick=()=>{$('help').hidden=!$('help').hidden;};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closePanel);
$('world').addEventListener('click',()=>{if(started&&!panel&&!locked&&!game.s.dead)lock();});
document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===$('world');if(!locked&&started&&!panel&&!game.s.dead)showPanel('pause');});
document.addEventListener('mousemove',e=>{if(!locked||panel)return;game.s.yaw-=e.movementX*.002;game.s.pitch=THREE.MathUtils.clamp(game.s.pitch-e.movementY*.002,-1.45,1.45);});
window.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('mousedown',e=>{if(!locked||panel||game.s.dead)return;if(e.button===0)attack();if(e.button===2)aim=true;});document.addEventListener('mouseup',e=>{if(e.button===2)aim=false;});
window.addEventListener('blur',()=>{keys.clear();if(started&&!panel&&!game.s.dead)showPanel('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started){keys.clear();if(!game.s.dead)showPanel('pause');save();}});window.addEventListener('beforeunload',save);
document.addEventListener('keydown',e=>{if(!started||game.s.dead)return;if(['Tab','Space','KeyM','KeyQ','KeyE','KeyF'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){if(panel)closePanel();else showPanel('pause');return;}if(e.code==='Tab'){panel==='inventory'?closePanel():showPanel('inventory');return;}if(e.code==='KeyM'){panel==='map-panel'?closePanel():showPanel('map-panel');return;}if(panel||document.pointerLockElement!==$('world'))return;keys.add(e.code);if(e.code==='KeyE')interact();if(e.code==='KeyQ')dogSearch();if(e.code==='KeyR'){game.reload();sound.noise(.2,.2,1200);}if(e.code==='KeyF'){flashlight=!flashlight;if(game.s.flashlight<=0)notify('手电电池已耗尽');}if(e.code==='KeyV')attack(true);if(/^Digit[1-4]$/.test(e.code))game.equip(Number(e.code.at(-1)));if(e.code==='Space'&&jump<=0&&game.s.stamina>12){jumpV=4.8;game.s.stamina-=8;}});document.addEventListener('keyup',e=>keys.delete(e.code));
function attack(melee=false){let d;if(melee){const crowbar=game.s.bag.find(i=>i.type==='crowbar');if(!crowbar){notify('需要一件近战工具');return;}const previous=game.s.equipped;game.s.equipped=crowbar.id;d=game.fire();game.s.equipped=previous;}else d=game.fire();if(!d)return;recoil=1;if(d.ammo){world.muzzle.intensity=7;sound.shot(game.weapon.type);for(const e of world.enemies){if(!e.userData.dead&&e.position.distanceTo(world.camera.position)<65){e.userData.state='search';e.userData.lastSeen={...game.s.position};e.userData.searchUntil=game.s.time+18;}}}else sound.melee();
 world.scene.updateMatrixWorld(true);ray.setFromCamera(v2,world.camera);ray.far=d.range;const targets=world.enemies.filter(e=>!e.userData.dead);const hits=ray.intersectObjects([...world.raycastSolids,...targets],true);if(hits.length){let node=hits[0].object;while(node.parent&&!targets.includes(node))node=node.parent;if(targets.includes(node)){node.userData.health-=d.damage;recoil=.7;world.impact(hits[0].point);sound.hit();if(node.userData.health<=0)killEnemy(node);else{node.userData.state='chase';node.userData.lastSeen={...game.s.position};node.userData.searchUntil=game.s.time+12;}}}}
function killEnemy(e){const u=e.userData;u.dead=true;u.respawn=game.s.time+300;world.assets.play(e,'Death',{once:true});const id=`remains-${game.s.time}-${world.enemies.indexOf(e)}`;game.s.corpses.push({id,x:e.position.x,z:e.position.z,items:u.animal?[item('meat',2)]:Math.random()<.4?[item(Math.random()<.5?'cloth':'bandage')]:[],expires:game.s.time+180});world.syncCorpses(game.s.corpses);}
function candidate(){const p=game.s.position;world.scene.updateMatrixWorld();const dir=new THREE.Vector3();world.camera.getWorldDirection(dir);let found=null,best=Infinity;for(const i of world.interactables){const dist=Math.hypot(i.x-p.x,i.z-p.z);if(dist>2.8)continue;const delta=new THREE.Vector3(i.x-world.camera.position.x,i.y-world.camera.position.y,i.z-world.camera.position.z).normalize();if(dir.dot(delta)<.66)continue;if(!world.visible(world.camera.position,{x:i.x,y:i.y,z:i.z}))continue;if(dist<best){found=i;best=dist;}}if(!found&&world.dog.position.distanceTo(world.camera.position)<3){const delta=world.dog.position.clone().add(new THREE.Vector3(0,.7,0)).sub(world.camera.position).normalize();if(dir.dot(delta)>.65)found={type:'dog',name:'阿灰'};}return found;}
function interact(){const c=candidate();if(!c)return;if(['safe','storage','loot','corpse'].includes(c.type)){if(c.type==='loot')game.crate(c.id,c.pool,c.x,c.z);showPanel('inventory',c);}else if(c.type==='map')showPanel('map-panel');else if(c.type==='radio'){sound.noise(.5,.4,1300);notify('「……北岸有动静……如果有人听见……照顾好自己。」');}else if(c.type==='bed'){if(game.s.hunger<25||game.s.thirst<25){notify('太饿或太渴，无法安心休息');return;}game.s.health=Math.min(100,game.s.health+18);game.s.stamina=100;game.s.hunger-=12;game.s.thirst-=16;game.s.dayTime=(game.s.dayTime+2)%24;game.s.dog.health=Math.min(100,game.s.dog.health+30);notify('短暂休息了两小时。饥饿和口渴并没有停下。');save();}else if(c.type==='bench')showPanel('inventory',{type:'bench'});else if(c.type==='dog'||c.type==='kennel')showPanel('inventory',{type:'dog'});}
function container(){if(!context)return null;const s=game.s;if(context.type==='safe')return {items:s.safe,cap:s.safeCapacity,name:'保险柜 · 死亡后保留'};if(context.type==='storage')return {items:s.storage,cap:30,name:'据点储物箱'};if(context.type==='loot'){const c=s.crates[context.id];return {items:c.items,cap:10,name:context.name};}if(context.type==='corpse'){const c=s.corpses.find(c=>c.id===context.id);return c?{items:c.items,cap:100,name:'遗落背包 · 限时保留'}:null;}return null;}
const rarity={common:'普通',uncommon:'较少见',rare:'稀有',epic:'非常稀有'};
function row(i,side){const d=ITEMS[i.type];const r=document.createElement('div');r.className=`item-row ${d.rarity}`;const icon=document.createElement('span');icon.className='item-icon';icon.textContent=d.icon;r.append(icon);const detail=document.createElement('div');const title=document.createElement('span');title.textContent=`${d.name}${i.qty>1?' × '+i.qty:''}`;detail.append(title);const sub=document.createElement('small');sub.textContent=`${rarity[d.rarity]} · ${(d.weight*i.qty).toFixed(2)} kg${i.durability!==undefined?' · 耐久 '+Math.round(i.durability)+'%':''}${i.loaded!==undefined?' · 已装弹 '+i.loaded:''}${i.id===game.s.equipped?' · 已装备':''}`;detail.append(sub);r.append(detail);const actions=document.createElement('div');const c=container();if(side==='bag'&&d.kind){const b=document.createElement('button');b.textContent=d.kind==='weapon'||d.kind==='armor'||d.kind==='backpack'?'装备':d.kind==='dogfood'?'喂狗':'使用';b.onclick=()=>{game.use(i.id);renderInventory();save();};actions.append(b);}const b=document.createElement('button');b.textContent=side==='bag'?(c?'存入':'丢弃'):'取出';b.onclick=()=>{if(c)game.transfer(side==='bag'?game.s.bag:c.items,side==='bag'?c.items:game.s.bag,i.id,side==='bag'?c.cap:game.s.capacity);else{const dropped={id:`drop-${game.s.time}-${i.id}`,x:game.s.position.x,z:game.s.position.z,items:[],expires:game.s.time+600};game.transfer(game.s.bag,dropped.items,i.id,100);game.s.corpses.push(dropped);world.syncCorpses(game.s.corpses);}renderInventory();save();};actions.append(b);r.append(actions);return r;}
function action(label,handler){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{handler();renderInventory();save();};$('panel-actions').append(b);}
function renderInventory(){const s=game.s,c=container();$('panel-title').textContent=context?.type==='bench'?'修整装备':context?.type==='dog'?'阿灰':c?context.name:'随身物资';$('inventory-summary').textContent=`负重 ${weight(s.bag).toFixed(1)} kg / 建议 24 kg　·　${s.bleeding?'正在出血　':''}${s.infection>0?'感染 '+Math.ceil(s.infection)+'%　':''}阿灰：健康 ${Math.round(s.dog.health)} / 饱腹 ${Math.round(s.dog.hunger)}`;$('bag-capacity').textContent=`${s.bag.length} / ${s.capacity} 格`;$('bag-list').replaceChildren(...s.bag.map(i=>row(i,'bag')));if(!s.bag.length)$('bag-list').innerHTML='<p class="empty">背包空空如也。</p>';$('container-title').textContent=c?`${c.name}　${c.items.length} / ${c.cap} 格`:'装备与伙伴';$('container-list').replaceChildren();if(c){c.items.forEach(i=>$('container-list').append(row(i,'container')));if(!c.items.length)$('container-list').innerHTML='<p class="empty">这里暂时没有物资。</p>';}else{$('container-list').innerHTML=`<p class="empty">${game.weapon?ITEMS[game.weapon.type].name:'空手'}<br><br>${s.armor?'防护背心 · 耐久 '+Math.round(s.armor.durability)+'%':'尚未穿戴护甲'}<br><br>手电电量 ${Math.round(s.flashlight)}%<br><br>阿灰不会永久死亡。重伤后失去战斗能力，返回据点可以恢复。</p>`;}$('panel-actions').replaceChildren();if(c)action('全部取出',()=>{for(const i of [...c.items])game.transfer(c.items,s.bag,i.id,s.capacity);});if(context?.type==='safe'){action('存入全部材料',()=>{for(const i of [...s.bag])if(!ITEMS[i.type].kind)game.transfer(s.bag,s.safe,i.id,s.safeCapacity);});action(`升级保险柜${s.safeCapacity<100?' · '+s.safeCapacity/2+' 金属 + 5 布料':' · 已满级'}`,()=>game.upgrade());}if(context?.type==='bench'){action('修理当前武器',()=>game.repair());action('制作绷带 · 2 布料',()=>craft(['cloth',2],item('bandage')));action('净化水 · 脏水 + 燃料',()=>{if(count(s.bag,'dirtywater')&&count(s.bag,'fuel')){const copy=s.bag.map(i=>({...i}));consume(copy,'dirtywater');consume(copy,'fuel');if(addTo(copy,item('water'),s.capacity)){s.bag=copy;game.notify('水已经煮沸净化');}else game.notify('背包空间不足');}else game.notify('缺少脏水或燃料');});action('烹饪 · 生肉 + 燃料',()=>{if(count(s.bag,'meat')&&count(s.bag,'fuel')){const copy=s.bag.map(i=>({...i}));consume(copy,'meat');consume(copy,'fuel');if(addTo(copy,item('canned'),s.capacity)){s.bag=copy;game.notify('制成一份安全的肉食');}else game.notify('背包空间不足');}else game.notify('缺少生肉或燃料');});}if(!c){action('喂阿灰 · 1 狗粮',()=>{const food=s.bag.find(i=>i.type==='dogfood');if(food)game.use(food.id);else game.notify('没有狗粮');});action('治疗阿灰 · 1 绷带',()=>{if(consume(s.bag,'bandage')){s.dog.health=Math.min(100,s.dog.health+35);game.notify('阿灰蹭了蹭你的手。');}else game.notify('没有绷带');});}if(context?.type==='loot')$('panel-hint').textContent='物资会在远离此处至少五分钟后随机补充。';else $('panel-hint').textContent='角色死亡会失去随身物资；据点保险柜和储物箱保存。';}
function craft([type,n],out){const bag=game.s.bag.map(i=>({...i}));if(!consume(bag,type,n)){game.notify('材料不足');return;}if(!addTo(bag,out,game.s.capacity)){game.notify('背包空间不足');return;}game.s.bag=bag;game.notify('制作完成');}
function dogSearch(){if(game.s.dog.health<20){notify('阿灰受伤了，先带它回家。');return;}if(game.s.time<searchCooldown){notify(`阿灰还在喘气 · ${Math.ceil(searchCooldown-game.s.time)} 秒后可以搜索`);return;}searchCooldown=game.s.time+40;searchUntil=game.s.time+18;const p=game.s.position;const candidates=world.interactables.filter(i=>['loot','corpse'].includes(i.type)&&Math.hypot(i.x-p.x,i.z-p.z)<28&&(!game.s.crates[i.id]||game.s.crates[i.id].items.length)).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z));dogTarget=candidates[0]||null;sound.bark(3);}
function updateDog(dt){const dog=world.dog,p=game.s.position;const near=world.enemies.filter(e=>!e.userData.dead&&e.position.distanceTo(dog.position)<16&&world.visible({x:dog.position.x,z:dog.position.z,y:.9},{x:e.position.x,z:e.position.z,y:1})).sort((a,b)=>a.position.distanceTo(dog.position)-b.position.distanceTo(dog.position))[0];let target;dogMode='跟着你';if(game.s.dog.health<20){dogMode='受伤 · 需要休息';target={x:p.x+1,z:p.z+2};dog.rotation.z=.2;}else{dog.rotation.z=0;if(near){target={x:near.position.x,z:near.position.z};dogMode='竖耳低吼';if(game.s.time-dogLastBark>9){sound.bark(Math.hypot(dog.position.x-p.x,dog.position.z-p.z));dogLastBark=game.s.time;}if(near.position.distanceTo(dog.position)<1.8&&game.s.time-dogLastAttack>1.7){near.userData.health-=18;world.dog.userData.attackUntil=game.s.time+.65;game.s.dog.health=Math.max(10,game.s.dog.health-5);dogLastAttack=game.s.time;if(near.userData.health<=0)killEnemy(near);}if(near.position.distanceTo(dog.position)>6&&near.userData.state!=='chase')target={x:dog.position.x,z:dog.position.z};}else if(dogTarget&&game.s.time<searchUntil){target=dogTarget;dogMode='嗅闻搜索';if(Math.hypot(target.x-dog.position.x,target.z-dog.position.z)<2){dogMode='停在物资旁';if(game.s.time-dogLastBark>5){sound.bark(4);dogLastBark=game.s.time;}}}else{dogTarget=null;const phase=game.s.time*.23;target={x:p.x+Math.cos(phase)*2.4-Math.sin(game.s.yaw)*1.2,z:p.z+Math.sin(phase)*2.4-Math.cos(game.s.yaw)*1.2};if(Math.sin(game.s.time*.35)>.9)dogMode='闻着地面';}}
 const dx=target.x-dog.position.x,dz=target.z-dog.position.z,dist=Math.hypot(dx,dz);if(dist>.9&&dogMode!=='闻着地面'){const speed=game.s.dog.health<20?2:dist>6?6:2.4;world.navigate(dog,target,dt,speed,.23);dog.userData.moving=true;}else dog.userData.moving=false;world.assets.play(dog,game.s.dog.health<20?'Idle_2_HeadLow':game.s.time<(dog.userData.attackUntil||0)?'Attack':dog.userData.moving?(dist>6?'Run':'Walk'):dogMode==='闻着地面'?'Idle_2_HeadLow':'Idle');if(Math.hypot(dog.position.x-p.x,dog.position.z-p.z)>32){for(const sign of [-1,1]){const x=p.x+sign*2,z=p.z+2;if(!world.collides(x,z,.23)){dog.position.set(x,0,z);break;}}}}
function updateEnemies(dt,moving,sprint,crouch){const p=game.s.position;for(const e of world.enemies){const u=e.userData;if(u.dead){if(game.s.time>u.respawn&&Math.hypot(p.x-e.position.x,p.z-e.position.z)>40){u.dead=false;u.health=u.animal?55:85;u.state='wander';e.rotation.z=0;e.position.set(u.home.x,0,u.home.z);}continue;}const dist=Math.hypot(p.x-e.position.x,p.z-e.position.z);const homeDist=Math.hypot(e.position.x,e.position.z-44);const sight=game.s.dayTime<6||game.s.dayTime>19?12:game.s.weather==='雾'?13:24;const toPlayer=new THREE.Vector3(p.x-e.position.x,0,p.z-e.position.z).normalize();const forward=new THREE.Vector3(-Math.sin(e.rotation.y),0,-Math.cos(e.rotation.y));const sees=dist<(crouch?sight*.55:sight)&&(forward.dot(toPlayer)>.15||dist<5)&&world.visible(e.position,p);const hears=moving&&dist<(sprint?15:crouch?2:6)*(['小雨','暴雨'].includes(game.s.weather)?.5:1);if((sees||hears)&&!game.inHome){u.state='chase';u.lastSeen={...p};u.searchUntil=game.s.time+12;}else if(u.state==='chase')u.state='search';if(u.state==='search'&&game.s.time>u.searchUntil){u.state='wander';u.lastSeen=null;}
 let target=u.state==='chase'?p:u.state==='search'?u.lastSeen:null;let speed=u.animal?2.8:1.5;if(game.inHome||homeDist<17){target=u.home;u.state='wander';}if(!target){u.timer+=dt;target={x:u.home.x+Math.sin(u.timer*.21)*4,z:u.home.z+Math.cos(u.timer*.17)*4};speed=.45;}
 if(dist<1.65&&u.state==='chase'&&!game.inHome&&game.s.time>u.attackAt){game.damage(u.animal?10:12,{bleed:Math.random()<.22,infect:!u.animal&&Math.random()<.18});u.attackAt=game.s.time+1.3;u.attackUntil=game.s.time+.7;sound.hit();}
 world.assets.play(e,game.s.time<(u.attackUntil||0)?'Punch':u.state==='chase'?'Run':u.state==='search'?'Walk':'Walk');const dx=target.x-e.position.x,dz=target.z-e.position.z,len=Math.hypot(dx,dz);if(len>.8){world.navigate(e,target,dt,speed,.32);e.position.y=Math.sin(game.s.time*5+u.home.x)*.025;u.legs?.forEach((leg,i)=>leg.rotation.x=Math.sin(game.s.time*6+i*Math.PI)*.35);}if(game.s.dead)break;}}
function worldEvent(){const s=game.s;if(s.time<s.nextEvent)return;s.nextEvent=s.time+100+Math.random()*140;const event=Math.floor(Math.random()*4);if(event===0){sound.shot('rifle');for(const e of world.enemies){if(!e.userData.dead&&e.position.z<-20){e.userData.state='search';e.userData.lastSeen={x:30,z:-62};e.userData.searchUntil=s.time+20;}}}else if(event===1){s.weather='暴雨';s.nextWeather=s.time+100;sound.noise(2,1,100);}else if(event===2){const x=s.position.x+12,z=s.position.z-14;if(!world.collides(x,z,.5)){s.corpses.push({id:`wanderer-${s.time}`,x,z,items:game.generateLoot('forest'),expires:s.time+600});world.syncCorpses(s.corpses);}}else{sound.noise(.7,.4,1300);}eventUntil=s.time+10;}
function showDeath(){deathShown=true;release();panel='death';for(const id of ['inventory','pause','map-panel'])$(id).hidden=true;$('death').hidden=false;$('death-text').textContent=`第 ${game.s.deaths} 次倒下 · 携带物资留在原地，15 分钟后消失。`;$('respawn').disabled=true;setTimeout(()=>$('respawn').disabled=false,2200);world.syncCorpses(game.s.corpses);save();}
$('respawn').onclick=()=>{game.respawn();$('death').hidden=true;deathShown=false;world.dog.position.set(game.s.position.x+2,0,game.s.position.z);searchUntil=0;dogTarget=null;lastHealth=100;lock();save();};
function drawMap(){const c=$('map'),ctx=c.getContext('2d'),w=c.width,h=c.height;const pos=(x,z)=>({x:(x+115)/230*w,y:(z+115)/230*h});ctx.fillStyle='#202c21';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#acba8820';for(let x=0;x<w;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.strokeStyle='#a3aa7860';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(pos(0,-112).x,0);ctx.lineTo(pos(0,112).x,h);ctx.stroke();for(const z of [24,-51]){ctx.beginPath();ctx.moveTo(pos(-78,z).x,pos(-78,z).y);ctx.lineTo(pos(78,z).x,pos(78,z).y);ctx.stroke();}for(const b of world.buildings){const p=pos(b.x-b.w/2,b.z-b.d/2);ctx.fillStyle='#8c977d';ctx.fillRect(p.x,p.y,b.w/230*w,b.d/230*h);}ctx.textAlign='center';for(const r of REGIONS){const p=pos(r.x,r.z);ctx.fillStyle=r.id==='home'?'#dec68b':'#c0c5ad';ctx.font='15px sans-serif';ctx.fillText((r.id==='home'?'◇ ':'')+r.name,p.x,p.y-24);ctx.fillStyle=r.danger>4?'#ba967d':'#849274';ctx.font='10px sans-serif';ctx.fillText(r.danger===0?'安全据点':r.danger>4?'高风险区域':'可探索区域',p.x,p.y-9);}for(const corpse of game.s.corpses){const p=pos(corpse.x,corpse.z);ctx.fillStyle='#d0a17a';ctx.font='18px sans-serif';ctx.fillText('×',p.x,p.y);}const p=pos(game.s.position.x,game.s.position.z);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-game.s.yaw);ctx.fillStyle='#f5d49a';ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(-6,7);ctx.lineTo(0,3);ctx.lineTo(6,7);ctx.closePath();ctx.fill();ctx.restore();ctx.textAlign='left';ctx.fillStyle='#bac2a1';ctx.font='12px monospace';ctx.fillText('N ↑',w-55,28);ctx.fillText('0 ───── 50 m',25,h-24);}
function updateHUD(){const s=game.s;for(const k of ['health','hunger','thirst','stamina']){$(k+'-bar').style.width=s[k]+'%';$(k+'-bar').style.background=s[k]<25?'#d28e70':'#c9d0b7';$(k+'-value').textContent=Math.ceil(s[k]);}$('conditions').textContent=[s.bleeding?'出血 · 需要绷带':'',s.infection>0?'感染 · 需要抗生素':'',s.temperature<35.5?'失温 · 尽快避雨':'',weight(s.bag)>24?'负重过高':''].filter(Boolean).join(' / ');$('dog-mood').textContent=dogMode;$('dog-vitals').textContent=`健康 ${Math.round(s.dog.health)} · 饱腹 ${Math.round(s.dog.hunger)}`;const w=game.weapon,d=w&&ITEMS[w.type];$('weapon-name').textContent=d?.name||'空手';$('ammo').innerHTML=d?.ammo?`${String(w.loaded).padStart(2,'0')} <span>/ ${count(s.bag,d.ammo)}</span>`:'— <span>/ 近战</span>';$('durability').textContent=`${game.reloadAt?'换弹中…':w?'耐久 '+Math.round(w.durability)+'%':''}　${flashlight?'电量 '+Math.round(s.flashlight)+'%':''}`;const r=game.region;$('location').innerHTML=`${r.name}<small>${game.inHome?'安全据点':r.danger>4?'高风险区域':'自由探索'}</small>`;const h=Math.floor(s.dayTime),m=Math.floor((s.dayTime-h)*60);$('clock').innerHTML=`第 ${String(Math.floor(s.time/2400)+1).padStart(2,'0')} 天 · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}<small>${s.weather} / ${Math.round(s.temperature-23)}°C</small>`;const headings=['北','东北','东','东南','南','西南','西','西北'];const angle=(((-s.yaw*180/Math.PI)%360)+360)%360;$('compass').innerHTML=`<span>${headings[(Math.round(angle/45)+7)%8]}</span><b>${headings[Math.round(angle/45)%8]}　${Math.round(angle)}°</b><span>${headings[(Math.round(angle/45)+1)%8]}</span><i>▾</i>`;const c=locked&&!panel?candidate():null;$('interaction').innerHTML=c?`<kbd>E</kbd>${c.type==='loot'?'搜索 ':''}${c.name}`:'';}
$('export-save').onclick=()=>{const blob=new Blob([JSON.stringify(game.s,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='荒城-生存存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};$('import-save').onclick=()=>$('save-file').click();$('save-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw Error('存档过大');const s=validateSave(JSON.parse(await file.text()));game.s=s;game.reloadAt=0;world.syncCorpses(s.corpses);world.dog.position.set(s.position.x+2,0,s.position.z);lastHealth=s.health;deathShown=false;save();notify('存档已导入');if(s.dead)showDeath();}catch(err){$('help').hidden=false;$('help').textContent='无法导入：'+err.message;}e.target.value='';};
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-lastClock)/1000,.05);lastClock=now;let moving=false,sprint=false,crouch=keys.has('KeyC');const active=started&&locked&&!panel&&!game.s.dead;
 if(active){const s=game.s;let x=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),z=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0);const len=Math.hypot(x,z);moving=len>0;sprint=keys.has('ShiftLeft')&&s.stamina>1&&moving&&!crouch&&!aim;let speed=(sprint?6.1:crouch?1.5:3.2)*(weight(s.bag)>24?.75:1)*(s.infection>30?.85:1);if(s.stamina<1)speed*=.65;if(s.weather==='暴雨')speed*=.88;if(len){x/=len;z/=len;world.move(s.position,(x*Math.cos(s.yaw)+z*Math.sin(s.yaw))*speed*dt,(-x*Math.sin(s.yaw)+z*Math.cos(s.yaw))*speed*dt,.32,jump);if(s.time-stepAt>(sprint?.29:.48)){sound.foot();stepAt=s.time;}}
 if(jump>0||jumpV>0){jumpV-=dt*12;jump=Math.max(0,jump+jumpV*dt);if(!jump)jumpV=0;}game.tick(dt,{sprinting:sprint,moving,flashlight});updateEnemies(dt,moving,sprint,crouch);updateDog(dt);worldEvent();if(s.health<lastHealth-.1)$('damage').style.opacity=.55;lastHealth=s.health;if(s.time-lastSave>10)save();if(Math.floor(s.time)%5===0)world.syncCorpses(s.corpses);}
 if(started&&game.s.dead&&!deathShown)showDeath();if(game.messages.length)notify(game.messages.splice(0).at(-1));$('notice').style.opacity=now<noticeUntil?1:0;$('damage').style.opacity=Math.max(0,Number($('damage').style.opacity||0)-dt*.5);recoil=Math.max(0,recoil-dt*5);if(now-lastHUD>120){updateHUD();lastHUD=now;}sound.update(game.s.weather,!active);world.updateVisual(game.s,dt,{menu:!started,flashlight,moving,aim,recoil,jump,crouch,reloading:!!game.reloadAt,paused:started&&!active});}
requestAnimationFrame(frame);
// Development-only hooks exercise the same state transitions used by gameplay.
if(import.meta.env.DEV)window.__survival={game,world,showPanel,renderInventory,save,attack,interact,dogSearch,get locked(){return locked;},get keys(){return [...keys];},get started(){return started;},get panel(){return panel;}};
