import * as THREE from 'three';
import {clone} from 'three/addons/utils/SkeletonUtils.js';
// The imported WRAD skeleton is posed in camera space with a two-bone arm solver.
export class ViewModel {
 constructor(camera,assets){this.assets=assets;this.root=new THREE.Group();camera.add(this.root);this.arms=clone(assets.models.get('arms').scene);this.arms.scale.setScalar(.12);this.arms.position.set(0,-.26,-.025);this.root.add(this.arms);this.bones={};this.arms.traverse(n=>{if(n.isBone){this.bones[n.name]=n;n.userData.rest=n.quaternion.clone();}if(n.isMesh){n.frustumCulled=false;n.castShadow=false;n.receiveShadow=false;n.renderOrder=0;const mat=n.material.clone();mat.depthTest=true;mat.depthWrite=true;mat.roughness=.9;n.material=mat;}});this.weapon=new THREE.Group();this.root.add(this.weapon);this.type=null;this.reloadStarted=0;this.wasReloading=false;this.setWeapon('crowbar');}
 pointBone(bone,end,target){this.root.updateMatrixWorld(true);const start=bone.getWorldPosition(new THREE.Vector3()),current=end.getWorldPosition(new THREE.Vector3()).sub(start).normalize(),wanted=target.clone().sub(start).normalize();const q=new THREE.Quaternion().setFromUnitVectors(current,wanted);const world=bone.getWorldQuaternion(new THREE.Quaternion()).premultiply(q);const parent=bone.parent.getWorldQuaternion(new THREE.Quaternion());bone.quaternion.copy(parent.invert().multiply(world));this.root.updateMatrixWorld(true);}
 poseArm(side,target,pole){const upper=this.bones['bicep'+side],lower=this.bones['forearm'+side],wrist=this.bones['wrist'+side];this.root.updateMatrixWorld(true);const start=upper.getWorldPosition(new THREE.Vector3());const elbow=lower.getWorldPosition(new THREE.Vector3()),hand=wrist.getWorldPosition(new THREE.Vector3());const a=start.distanceTo(elbow),b=elbow.distanceTo(hand),t=this.root.localToWorld(target.clone()),delta=t.clone().sub(start),distance=Math.min(delta.length(),a+b-.001);const forward=delta.normalize();const sideDirection=this.root.localToWorld(pole.clone()).sub(start);sideDirection.addScaledVector(forward,-sideDirection.dot(forward)).normalize();const along=(a*a-b*b+distance*distance)/(2*distance),height=Math.sqrt(Math.max(0,a*a-along*along));const desiredElbow=start.clone().addScaledVector(forward,along).addScaledVector(sideDirection,height);this.pointBone(upper,lower,desiredElbow);this.pointBone(lower,wrist,t);const socket=this.bones['socket'+side];const handEnd=t.clone().add(new THREE.Vector3(0,.035,-.065).transformDirection(this.root.matrixWorld).multiplyScalar(.07));this.pointBone(wrist,socket,handEnd);}
 curlFingers(side){for(const finger of ['pinky','ring','middle','index','thumb']){const first=this.bones['finger_'+finger+'1'+side],second=this.bones['finger_'+finger+'2'+side];this.root.updateMatrixWorld(true);const forward=second.getWorldPosition(new THREE.Vector3()).sub(first.getWorldPosition(new THREE.Vector3())).normalize();const inward=new THREE.Vector3(side==='r'?-1:1,0,0).transformDirection(this.root.matrixWorld);const axis=forward.clone().cross(inward).normalize();for(let i=1;i<=3;i++){const bone=this.bones['finger_'+finger+i+side];const angle=finger==='thumb'?.18:finger==='index'?[.45,.55,.4][i-1]:[.85,1.1,.75][i-1];const delta=new THREE.Quaternion().setFromAxisAngle(axis,angle);const world=bone.getWorldQuaternion(new THREE.Quaternion()).premultiply(delta);bone.quaternion.copy(bone.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(world));this.root.updateMatrixWorld(true);}}}
 setWeapon(type){if(this.type===type)return;this.type=type;this.weapon.clear();if(!type)return;const key=type==='crowbar'?'bat':type==='marksman'?'rifle':type;const model=clone(this.assets.models.get(key).scene);model.rotation.y=Math.PI;model.scale.setScalar(type==='crowbar'?.7:type==='pistol'?.38:type==='shotgun'?.65:.54);model.position.set(0,0,0);if(type==='crowbar'){model.rotation.set(.6,Math.PI,.15);model.position.set(0,.01,-.04);}model.traverse(n=>{if(n.isMesh){n.renderOrder=0;n.frustumCulled=false;n.castShadow=false;n.receiveShadow=false;const mat=n.material.clone();mat.depthTest=true;mat.depthWrite=true;mat.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n diffuseColor.rgb = mix(vec3(dot(diffuseColor.rgb, vec3(0.299,0.587,0.114))), diffuseColor.rgb, 0.28) * 0.78;');};mat.customProgramCacheKey=()=> 'weathered-view-weapon';n.material=mat;}});this.weapon.add(model);}
 update(dt,{type,aim,recoil,moving,time,reloading,melee=false}){this.setWeapon(type);if(reloading&&!this.wasReloading)this.reloadStarted=time;this.wasReloading=reloading;const reload=reloading?Math.sin(Math.min(1,(time-this.reloadStarted)/(type==='shotgun'?2.5:1.6))*Math.PI):0;this.root.position.set(aim?-.17:0,(moving?Math.sin(time*9)*.007:0)-reload*.07+(aim?(type==='pistol'?.12:.04):0),aim?-.20:0);this.root.rotation.set(recoil*.065+reload*.22,0,reload*.22);for(const bone of Object.values(this.bones))bone.quaternion.copy(bone.userData.rest);const meleeSwing=type==='crowbar'?recoil:0;const right=new THREE.Vector3(.19-meleeSwing*.22,-.28+meleeSwing*.08,-.43-meleeSwing*.18);const left=type==='pistol'?new THREE.Vector3(.09,-.29,-.43):type==='crowbar'?new THREE.Vector3(-.26,-.46,-.15):new THREE.Vector3(.10,-.27,-.54);left.y-=reload*.22;left.z+=reload*.16;this.poseArm('r',right,new THREE.Vector3(.48,-.65,.02));this.poseArm('l',left,new THREE.Vector3(-.5,-.64,.02));this.curlFingers('r');this.curlFingers('l');
 this.weapon.position.copy(right).add(new THREE.Vector3(0,.04,-.035));this.weapon.position.z+=recoil*.025;this.weapon.rotation.set(recoil*.12+meleeSwing*.65,meleeSwing*-.35,0);this.root.updateMatrixWorld(true);}
}
