import * as THREE from 'three';
import {clone} from 'three/addons/utils/SkeletonUtils.js';
// The imported WRAD skeleton is posed in camera space with a two-bone arm solver.
export class ViewModel {
 constructor(camera,assets){this.camera=camera;this.assets=assets;this.root=new THREE.Group();camera.add(this.root);this.arms=clone(assets.models.get('arms').scene);this.arms.scale.setScalar(.12);this.arms.position.set(0,-.26,-.025);this.root.add(this.arms);this.bones={};this.arms.traverse(n=>{if(n.isBone){this.bones[n.name]=n;n.userData.rest=n.quaternion.clone();}if(n.isMesh){n.frustumCulled=false;n.castShadow=false;n.receiveShadow=false;n.renderOrder=0;const mat=n.material.clone();mat.depthTest=true;mat.depthWrite=true;mat.roughness=.9;n.material=mat;}});this.weapon=new THREE.Group();this.root.add(this.weapon);this.type=null;this.reloadStarted=0;this.wasReloading=false;this.meleeTime=0;this.contactTime=0;this.setWeapon('crowbar');}
 pointBone(bone,end,target){this.root.updateMatrixWorld(true);const start=bone.getWorldPosition(new THREE.Vector3()),current=end.getWorldPosition(new THREE.Vector3()).sub(start).normalize(),wanted=target.clone().sub(start).normalize();const q=new THREE.Quaternion().setFromUnitVectors(current,wanted);const world=bone.getWorldQuaternion(new THREE.Quaternion()).premultiply(q);const parent=bone.parent.getWorldQuaternion(new THREE.Quaternion());bone.quaternion.copy(parent.invert().multiply(world));this.root.updateMatrixWorld(true);}
 poseArm(side,target,pole){const upper=this.bones['bicep'+side],lower=this.bones['forearm'+side],wrist=this.bones['wrist'+side];this.root.updateMatrixWorld(true);const start=upper.getWorldPosition(new THREE.Vector3());const elbow=lower.getWorldPosition(new THREE.Vector3()),hand=wrist.getWorldPosition(new THREE.Vector3());const a=start.distanceTo(elbow),b=elbow.distanceTo(hand),t=this.root.localToWorld(target.clone()),delta=t.clone().sub(start),distance=Math.min(delta.length(),a+b-.001);const forward=delta.normalize();const sideDirection=this.root.localToWorld(pole.clone()).sub(start);sideDirection.addScaledVector(forward,-sideDirection.dot(forward)).normalize();const along=(a*a-b*b+distance*distance)/(2*distance),height=Math.sqrt(Math.max(0,a*a-along*along));const desiredElbow=start.clone().addScaledVector(forward,along).addScaledVector(sideDirection,height);this.pointBone(upper,lower,desiredElbow);this.pointBone(lower,wrist,t);const socket=this.bones['socket'+side];const handEnd=t.clone().add(new THREE.Vector3(0,.035,-.065).transformDirection(this.root.matrixWorld).multiplyScalar(.07));this.pointBone(wrist,socket,handEnd);}
 curlFingers(side){for(const finger of ['pinky','ring','middle','index','thumb']){const first=this.bones['finger_'+finger+'1'+side],second=this.bones['finger_'+finger+'2'+side];this.root.updateMatrixWorld(true);const forward=second.getWorldPosition(new THREE.Vector3()).sub(first.getWorldPosition(new THREE.Vector3())).normalize();const inward=new THREE.Vector3(side==='r'?-1:1,0,0).transformDirection(this.root.matrixWorld);const axis=forward.clone().cross(inward).normalize();for(let i=1;i<=3;i++){const bone=this.bones['finger_'+finger+i+side];const angle=finger==='thumb'?.18:finger==='index'?[.45,.55,.4][i-1]:[.85,1.1,.75][i-1];const delta=new THREE.Quaternion().setFromAxisAngle(axis,angle);const world=bone.getWorldQuaternion(new THREE.Quaternion()).premultiply(delta);bone.quaternion.copy(bone.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(world));this.root.updateMatrixWorld(true);}}}
 setWeapon(type){if(this.type===type)return;this.type=type;this.weapon.clear();if(!type)return;const key=type==='crowbar'?'bat':type==='marksman'?'rifle':type;const model=clone(this.assets.models.get(key).scene);model.rotation.y=Math.PI;model.scale.setScalar(type==='crowbar'?.55:type==='pistol'?.38:type==='shotgun'?.65:.54);model.position.set(0,0,0);if(type==='crowbar'){model.rotation.set(0,0,0);model.position.set(0,0,.134);}model.traverse(n=>{if(n.isMesh){n.renderOrder=0;n.frustumCulled=false;n.castShadow=false;n.receiveShadow=false;const mat=n.material.clone();mat.depthTest=true;mat.depthWrite=true;mat.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n diffuseColor.rgb = mix(vec3(dot(diffuseColor.rgb, vec3(0.299,0.587,0.114))), diffuseColor.rgb, 0.28) * 0.78;');};mat.customProgramCacheKey=()=> 'weathered-view-weapon';n.material=mat;}});this.weapon.add(model);}
 // A power grip is authored in wrist space: fingers close toward the palm (-X),
 // and the bat runs across the fist (+Z, toward the thumb). It never moves independently.
 swing(){this.meleeTime=.62;}
 contact(){this.contactTime=.075;}
 poseBat(dt,{moving,time}){
  const held=Math.min(dt,this.contactTime);this.contactTime=Math.max(0,this.contactTime-dt);
  this.meleeTime=Math.max(0,this.meleeTime-(dt-held));
  const phase=this.meleeTime>0?1-this.meleeTime/.62:0;
  const smooth=t=>t*t*(3-2*t);
  const keys=[{t:0,p:[.21,-.22,-.52],r:[-.35,0,-.20]},{t:.2,p:[.30,-.24,-.33],r:[-.3,-.25,-.48]},{t:.48,p:[-.12,-.31,-.57],r:[.5,.25,1.0]},{t:1,p:[.21,-.22,-.52],r:[-.35,0,-.20]}];
  const end=keys.findIndex(k=>k.t>phase),i=end<0?keys.length-2:Math.max(0,end-1),a=keys[i],b=keys[i+1],t=smooth((phase-a.t)/(b.t-a.t));
  const wrist=new THREE.Vector3().fromArray(a.p).lerp(new THREE.Vector3().fromArray(b.p),t);
  this.root.position.set(Math.min(0,this.camera.aspect-1.25)*.13+(moving?Math.sin(time*4.5)*.006:0),moving?Math.sin(time*9)*.006:Math.sin(time*1.7)*.002,0);this.root.rotation.set(0,0,0);
  this.poseArm('r',wrist,new THREE.Vector3(.55,-.7,.05));
  this.poseArm('l',new THREE.Vector3(-.29,-.57,-.2),new THREE.Vector3(-.5,-.7,.05));
  const basis=new THREE.Matrix4().makeBasis(new THREE.Vector3(.8,0,.6),new THREE.Vector3(.6,0,-.8),new THREE.Vector3(0,1,0));
  const rotation=new THREE.Euler(...a.r.map((v,j)=>THREE.MathUtils.lerp(v,b.r[j],t)));
  const q=new THREE.Quaternion().setFromRotationMatrix(basis).premultiply(new THREE.Quaternion().setFromEuler(rotation));
  const hand=this.bones.wristr;
  hand.quaternion.copy(hand.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(this.root.getWorldQuaternion(new THREE.Quaternion())).multiply(q));
  for(const finger of ['pinky','ring','middle','index'])for(let j=1;j<=3;j++){const bone=this.bones['finger_'+finger+j+'r'];bone.quaternion.copy(bone.userData.rest).multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),[1.05,1.35,.85][j-1]));}
  for(let j=1;j<=3;j++){const bone=this.bones['finger_thumb'+j+'r'];bone.quaternion.copy(bone.userData.rest).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(.12,0,[.35,.65,.6][j-1])));}
  this.root.updateMatrixWorld(true);
  this.pointBone(this.bones.finger_thumb1r,this.bones.finger_thumb2r,hand.localToWorld(new THREE.Vector3(-.38,.40,.26)));
  this.pointBone(this.bones.finger_thumb2r,this.bones.finger_thumb3r,hand.localToWorld(new THREE.Vector3(-.50,.64,.14)));
  this.curlFingers('l');this.root.updateMatrixWorld(true);
  this.weapon.position.copy(this.root.worldToLocal(hand.localToWorld(new THREE.Vector3(-.25,.67,0))));
  this.weapon.quaternion.copy(this.root.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(hand.getWorldQuaternion(new THREE.Quaternion())));
  this.root.updateMatrixWorld(true);
 }
 update(dt,{type,aim,recoil,moving,time,reloading}){if(this.meleeTime>0)type='crowbar';this.setWeapon(type);if(type==='crowbar'){for(const bone of Object.values(this.bones))bone.quaternion.copy(bone.userData.rest);this.poseBat(dt,{moving,time});return;}if(reloading&&!this.wasReloading)this.reloadStarted=time;this.wasReloading=reloading;const reload=reloading?Math.sin(Math.min(1,(time-this.reloadStarted)/(type==='shotgun'?2.5:1.6))*Math.PI):0;this.root.position.set(aim?-.17:0,(moving?Math.sin(time*9)*.007:0)-reload*.07+(aim?(type==='pistol'?.12:.04):0),aim?-.20:0);this.root.rotation.set(recoil*.065+reload*.22,0,reload*.22);for(const bone of Object.values(this.bones))bone.quaternion.copy(bone.userData.rest);const right=new THREE.Vector3(.19,-.28,-.43);const left=type==='pistol'?new THREE.Vector3(.09,-.29,-.43):new THREE.Vector3(.10,-.27,-.54);left.y-=reload*.22;left.z+=reload*.16;this.poseArm('r',right,new THREE.Vector3(.48,-.65,.02));this.poseArm('l',left,new THREE.Vector3(-.5,-.64,.02));this.curlFingers('r');this.curlFingers('l');
 this.weapon.position.copy(right).add(new THREE.Vector3(0,.04,-.035));this.weapon.position.z+=recoil*.025;this.weapon.rotation.set(recoil*.12,0,0);this.root.updateMatrixWorld(true);}
}
