import * as THREE from 'three';
import {ViewModel} from './viewmodel.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
const seeded=(seed=726)=>()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
export class World {
 constructor(canvas,assets){this.assets=assets;this.rng=seeded();this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#8e9b86');this.scene.fog=new THREE.FogExp2('#8e9b86',.014);this.camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.07,240);this.camera.rotation.order='YXZ';this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.solids=[];this.raycastSolids=[];this.interactables=[];this.buildings=[];this.enemies=[];this.corpseModels=new Map();this.effects=[];this.time=0;this.walkableCache=new Map();
 this.m={concrete:this.material('#77776a','concrete'),brick:this.material('#716753','brick'),plaster:this.material('#a4a28a','plaster'),dark:this.material('#343c36'),roof:this.material('#4a5145','metal'),metal:this.material('#667064','metal'),rust:this.material('#76604a','metal'),wood:this.material('#74684e','wood'),bark:this.material('#595644','wood'),leaf:this.material('#546343'),grass:this.material('#67734e'),glass:this.material('#536d68'),black:this.material('#232b27'),road:this.material('#51584e','road'),ground:this.material('#697352','ground'),red:this.material('#76574b'),cloth:this.material('#575f4d'),white:this.material('#cac5a7')};
 const hemi=new THREE.HemisphereLight('#c9d0cf','#383f2f',2.5);this.scene.add(hemi);this.hemi=hemi;this.sun=new THREE.DirectionalLight('#eef0df',3.1);this.sun.position.set(-35,65,28);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-85,right:85,top:85,bottom:-85,near:1,far:180});this.sun.shadow.bias=-.0005;this.scene.add(this.sun);this.scene.add(this.sun.target);
 this.build();this.batchStatics();this.dog=this.makeDog();this.dog.position.set(3,0,24);this.scene.add(this.dog);this.makeViewWeapon();this.flashlight=new THREE.SpotLight('#fff0c4',0,45,.43,.6,1.2);this.camera.add(this.flashlight);this.flashlight.target.position.set(0,-.3,-20);this.camera.add(this.flashlight.target);this.scene.add(this.camera);this.makeRain();
 addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);});}
 batchStatics(){this.scene.updateMatrixWorld(true);const buckets=new Map();const interactive=new Set(this.interactables.map(i=>i.mesh));const nodes=[];this.scene.traverse(n=>nodes.push(n));for(const node of nodes){let protectedNode=false;for(let p=node;p;p=p.parent)if(interactive.has(p))protectedNode=true;if(!node.isMesh||node.isInstancedMesh||protectedNode||node===this.grass)continue;const at=new THREE.Vector3().setFromMatrixPosition(node.matrixWorld);const key=node.material.uuid+':'+Math.floor(at.x/32)+':'+Math.floor(at.z/32);if(!buckets.has(key))buckets.set(key,{material:node.material,geometries:[]});buckets.get(key).geometries.push(node.geometry.clone().applyMatrix4(node.matrixWorld));node.parent.remove(node);}for(const b of buckets.values()){const geometry=mergeGeometries(b.geometries,false);b.geometries.forEach(g=>g.dispose());if(!geometry)continue;const mesh=new THREE.Mesh(geometry,b.material);mesh.castShadow=true;mesh.receiveShadow=true;this.scene.add(mesh);}}
 material(color,pattern){let map;if(pattern){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,128,128);for(let i=0;i<1900;i++){const a=this.rng()*.08;ctx.fillStyle=this.rng()>.5?`rgba(0,0,0,${a})`:`rgba(255,255,225,${a})`;ctx.fillRect(this.rng()*128,this.rng()*128,this.rng()*4+1,this.rng()*3+1);}ctx.strokeStyle='#242b252d';ctx.lineWidth=1;if(pattern==='brick'){for(let y=0;y<128;y+=16){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(128,y);ctx.stroke();for(let x=(y%32?0:16);x<128;x+=32){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+16);ctx.stroke();}}}if(pattern==='wood'||pattern==='metal'){for(let x=0;x<128;x+=16){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,128);ctx.stroke();}}map=new THREE.CanvasTexture(c);map.wrapS=map.wrapT=THREE.RepeatWrapping;map.colorSpace=THREE.SRGBColorSpace;map.repeat.set(2,2);map.anisotropy=4;}return new THREE.MeshStandardMaterial({color:map?'#ffffff':color,map,roughness:.95});}
 box(w,h,d,mat,x,y,z,parent=this.scene,solid=false){const geometry=new THREE.BoxGeometry(w,h,d);if(mat.map){const uv=geometry.attributes.uv,n=geometry.attributes.normal;for(let i=0;i<uv.count;i++){const sx=Math.abs(n.getX(i))>.5?d:w,sy=Math.abs(n.getY(i))>.5?d:h;uv.setXY(i,uv.getX(i)*sx/3,uv.getY(i)*sy/3);}}const o=new THREE.Mesh(geometry,mat);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);if(solid){this.solids.push({minX:x-w/2,maxX:x+w/2,minZ:z-d/2,maxZ:z+d/2,minY:y-h/2,maxY:y+h/2});this.raycastSolids.push(o);}return o;}
 cylinder(rt,rb,h,mat,x,y,z,parent=this.scene,segments=8){const o=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,segments),mat);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 sign(text,w,h,x,y,z,{color='#d5d4b4',bg='#344139',rotation=0,size=60}={}){const c=document.createElement('canvas');c.width=768;c.height=160;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,768,160);ctx.strokeStyle=color;ctx.globalAlpha=.4;ctx.strokeRect(9,9,750,142);ctx.globalAlpha=1;ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`${size}px "Songti SC",serif`;ctx.fillText(text,384,81);for(let i=0;i<170;i++){ctx.fillStyle='#26302525';ctx.fillRect(this.rng()*768,this.rng()*160,2+this.rng()*40,1+this.rng()*4);}const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshStandardMaterial({map,roughness:.9,side:THREE.DoubleSide}));mesh.position.set(x,y,z);mesh.rotation.y=rotation;this.scene.add(mesh);return mesh;}
 addInteract(type,name,x,y,z,mesh,extra={}){const entry={type,name,x,y,z,mesh,...extra};this.interactables.push(entry);return entry;}
 crate(x,z,pool,id,name='储物箱',kind='crate'){let m;if(kind==='cabinet'){m=this.box(1.1,1.7,.55,this.m.metal,x,.85,z);for(let k=0;k<3;k++)this.box(.8,.035,.06,this.m.black,x,.4+k*.48,z+.3);}else{m=this.box(1.05,.68,.65,pool==='medical'?this.m.white:this.m.wood,x,.42,z);this.box(1.1,.06,.7,this.m.dark,x,.77,z);this.box(.12,.22,.02,this.m.rust,x,.56,z+.335);for(const dx of [-.4,.4])this.box(.06,.7,.69,this.m.dark,x+dx,.42,z);}this.addInteract('loot',name,x,.7,z,m,{id,pool});return m;}
 building(x,z,w,d,name,pool,{height=4.5,mat=this.m.plaster,roof=true}={}){this.buildings.push({x,z,w,d,name});this.box(w,.15,d,this.m.concrete,x,.02,z);const wall=(ww,hh,dd,xx,yy,zz)=>this.box(ww,hh,dd,mat,xx,yy,zz,this.scene,true);wall(w,height,.35,x,height/2,z-d/2);wall(.35,height,d,x-w/2,height/2,z);wall(.35,height,d,x+w/2,height/2,z);const side=(w-2.4)/2;wall(side,height,.35,x-(w+2.4)/4,height/2,z+d/2);wall(side,height,.35,x+(w+2.4)/4,height/2,z+d/2);wall(2.4,height-2.7,.35,x,2.7+(height-2.7)/2,z+d/2);if(roof)this.box(w+.7,.3,d+.7,this.m.roof,x,height+.08,z,this.scene,true);
 for(const dx of [-w*.3,w*.3]){this.box(2,1.4,.08,this.m.dark,x+dx,2,z+d/2+.2);this.box(.08,1.5,.12,this.m.wood,x+dx,2,z+d/2+.26);this.box(2.1,.08,.12,this.m.wood,x+dx,2,z+d/2+.26);const plank=this.box(2.2,.17,.12,this.m.wood,x+dx,2.2,z+d/2+.34);plank.rotation.z=dx>0?.22:-.3;}
 this.sign(name,Math.min(w-1,7),.88,x,height-.65,z+d/2+.23);this.box(w+.5,.12,1.5,this.m.roof,x,2.9,z+d/2+.6);
 if(pool!=='home'){this.box(2.5,.85,.65,this.m.wood,x-w*.28,.45,z-d*.22,this.scene,true);this.crate(x-w*.27,z-d*.22+1,pool,`${pool}-${x}-${z}-1`,'旧柜子');this.crate(x+w*.29,z-d*.31,pool,`${pool}-${x}-${z}-2`,pool==='medical'||pool==='hospital'?'医疗柜':'储物柜','cabinet');this.shelf(x+w*.3,z+.5,pool);this.crate(x+w*.3,z+.7,pool,`${pool}-${x}-${z}-3`,'货架物资');}
 // Peeling plaster, loose bricks, window ledges and ivy break up clean silhouettes.
 for(let i=0;i<5;i++){this.box(.5+this.rng()*1.2,.2+this.rng()*.6,.018,this.m.concrete,x-w*.45+this.rng()*w*.9,.3+this.rng(),z+d/2+.186);}
 for(let j=0;j<6;j++){const dx=x-w/2+.3+this.rng()*.7;this.bush(dx,z+d/2+.5,.4+this.rng()*.35);}
 const light=new THREE.PointLight('#c4c9a5',1.4,11,1.8);light.position.set(x,3,z);this.scene.add(light);}
 shelf(x,z,pool){for(const dx of [-.63,.63])this.box(.055,2,.5,this.m.metal,x+dx,1,z);for(let y=.2;y<2;y+=.55){this.box(1.4,.05,.55,this.m.metal,x,y,z);for(let j=0;j<3;j++){if(this.rng()>.6)continue;this.box(.15,.2,.14,pool==='medical'?this.m.white:this.m.rust,x-.45+j*.4,y+.13,z);}}}
 bush(x,z,s=1){const model=this.assets.create('bush',{height:s*1.2,rotation:this.rng()*6.28});model.position.set(x,0,z);this.scene.add(model);}
 tree(x,z,s=1){const tree=this.assets.create(this.rng()<.15?'deadTree':'pine',{height:(6+this.rng()*2)*s,rotation:this.rng()*Math.PI*2});tree.position.set(x,0,z);this.scene.add(tree);this.solids.push({minX:x-.28,maxX:x+.28,minZ:z-.28,maxZ:z+.28,minY:0,maxY:8});}
 car(x,z,rot=0){const g=this.assets.create(z<-40?'truck':'pickup',{length:4.3,rotation:0});g.position.set(x,0,z);g.rotation.y=rot;this.scene.add(g);this.solids.push({minX:x-1.5,maxX:x+1.5,minZ:z-2,maxZ:z+2,minY:0,maxY:1.7});g.traverse(n=>{if(n.isMesh)this.raycastSolids.push(n);});const trunk=new THREE.Vector3(0,.8,-2.1).applyAxisAngle(new THREE.Vector3(0,1,0),rot).add(g.position);this.addInteract('loot','汽车后备箱',trunk.x,trunk.y,trunk.z,g,{id:`car-${x}-${z}`,pool:'house'});}
 build(){const m=this.m;this.box(260,.2,260,m.ground,0,-.2,0);this.box(9,.025,230,m.road,0,-.075,0);this.box(155,.025,7,m.road,0,-.065,24);this.box(145,.025,7,m.road,0,-.065,-51);for(let z=-106;z<110;z+=7)this.box(.1,.008,2.9,m.white,0,-.05,z);for(const x of [-5.2,5.2])this.box(.4,.15,225,m.concrete,x,-.025,0);
 // A roofed, open-front fuel station with a sheltered permanent home.
 this.building(-7,47,12,9,'松 岭 加 油 站','home',{height:3.8});this.box(18,.35,10,m.roof,3,4.1,36);this.box(18,.52,.15,m.red,3,3.83,41.05);for(const x of [-4,10])this.box(.18,4,.18,m.metal,x,2,39);for(const x of [1,5]){this.box(.85,1.6,.7,m.white,x,.8,37);this.box(.63,.43,.05,m.black,x,1.12,37.37);this.box(.7,.15,.77,m.red,x,1.65,37);const hose=new THREE.Mesh(new THREE.TorusGeometry(.35,.035,6,12,Math.PI*1.5),m.black);hose.position.set(x+.5,.95,37);this.scene.add(hose);}
 // Home interactions are physically reachable behind the station entrance.
 const safe=this.box(1.1,1.4,.85,m.dark,-10,.7,45);this.box(.86,1.16,.04,m.metal,-10,.7,45.45);this.cylinder(.13,.13,.08,m.rust,-10,.75,45.5).rotation.x=Math.PI/2;this.addInteract('safe','保险柜',-10,.9,45.6,safe);this.sign('保险柜 · 永久储存',2,.34,-10,1.85,45.47,{size:43});
 const storage=this.box(1.6,.7,.8,m.wood,-3,.35,44);this.addInteract('storage','储物箱',-3,.7,44,storage);
 const bench=this.box(2.2,.12,1,m.wood,-10,.8,49);for(const x of [-10.9,-9.1])this.box(.1,.8,.8,m.metal,x,.4,49);this.box(.6,.17,.3,m.rust,-10,.95,49);this.addInteract('bench','工作台',-10,1,49,bench);
 const bed=this.box(1,.4,2.2,m.cloth,-3,.4,49);this.box(.8,.12,.45,m.white,-3,.66,48.3);this.addInteract('bed','简易床',-3,.6,49,bed);
 const radio=this.box(.4,.25,.18,m.dark,-8,.95,49);this.addInteract('radio','短波收音机',-8,1,49,radio);this.cylinder(.015,.015,.7,m.metal,-8.1,1.4,49);
 const board=this.box(1.8,1.3,.08,m.wood,-7,1.9,42.65);this.sign('松 岭 区 域 图',1.5,.7,-7,2,42.71,{bg:'#a9ae8d',color:'#344535',size:50});this.addInteract('map','墙上地图',-7,1.8,43,board);
 const kennel=this.box(1.5,.9,1.6,m.wood,12,.45,45);this.box(.65,.75,.04,m.black,12,.39,45.82);this.box(1.8,.13,1.9,m.roof,12,1,45);this.addInteract('kennel','阿灰的窝',12,.7,46,kennel);
 this.sign('松岭  /  SONGLING',4.5,.9,8,3,29,{size:45});this.box(.12,3,.12,m.rust,8,1.5,29);
 this.building(-22,9,12,11,'青石巷 07','house');this.building(-39,8,11,10,'青石巷 09','house',{mat:m.brick,height:5.2});this.building(-23,-8,11,10,'青石巷 03','house',{mat:m.brick});this.building(20,5,16,12,'惠 民 超 市','food',{height:4.7});this.building(-26,-28,14,12,'松 岭 卫 生 所','medical');this.sign('✚',1.1,1.1,-26,4.5,-21.75,{bg:'#64705a',color:'#dadac3',size:90});this.building(23,-32,16,14,'松 岭 派 出 所','police',{height:5.5,mat:m.concrete});
 this.building(54,-67,21,15,'北 岸 机 修 厂','industrial',{height:6,mat:m.brick});for(let i=0;i<3;i++){this.cylinder(2.1,2.1,6,m.metal,69+i*5,3,-68);this.cylinder(2.15,2.15,.2,m.rust,69+i*5,6,-68);}for(let i=0;i<5;i++){this.cylinder(.4,.4,1,m.rust,42+i*.9,.5,-56);}
 this.building(-62,43,15,12,'西 郊 农 舍','farm',{mat:m.wood,height:4});for(let i=0;i<7;i++)for(let j=0;j<9;j++){const x=-74+i*2,z=57+j*1.3;this.box(1.6,.07,.7,m.bark,x,0,z);if(this.rng()>.3)this.bush(x,z,.35);}this.building(-71,-48,9,8,'巡 林 小 屋','forest',{mat:m.wood,height:3.7});this.crate(-59,-58,'forest','hidden-camp','被草遮住的背包');
 this.building(-22,-83,24,17,'松 岭 县 医 院','hospital',{height:5.6,mat:m.concrete});this.box(24,3.5,17,m.concrete,-22,7.6,-83);for(let i=0;i<7;i++){this.box(1.6,1.8,.07,m.glass,-32+i*3.3,7.5,-74.45);this.box(.08,1.8,.09,m.dark,-32+i*3.3,7.5,-74.38);}this.sign('✚',1.8,1.8,-22,10,-74.3,{bg:'#677158',color:'#dadbc3',size:90});
 for(const [x,z,r] of [[-2,13,.17],[7,-16,.45],[-8,-52,-.3],[30,24,1.7],[-46,25,1.3],[15,-60,.3],[4,69,-.5]])this.car(x,z,r);
 for(let z=-82;z<80;z+=24){this.cylinder(.045,.09,6,m.metal,6,3,z);this.box(1.1,.08,.12,m.metal,5.5,5.95,z);this.box(.55,.07,.3,m.dark,5,5.9,z);}
 for(let i=0;i<180;i++){const x=this.rng()*230-115,z=this.rng()*230-115;if(Math.abs(x)<11||Math.abs(z-24)<6||Math.abs(z+51)<6||this.buildings.some(b=>Math.abs(x-b.x)<b.w/2+3&&Math.abs(z-b.z)<b.d/2+3)||Math.hypot(x,z-40)<17)continue;this.tree(x,z,.7+this.rng()*.8);}
 this.addImportedProps();this.makeGrass();for(let i=0;i<60;i++){const x=this.rng()*190-95,z=this.rng()*190-95;if(this.buildings.some(b=>Math.abs(x-b.x)<b.w/2&&Math.abs(z-b.z)<b.d/2))continue;const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.2+this.rng()*.5,0),m.concrete);rock.position.set(x,.15,z);rock.scale.set(1.7,.5,1);rock.rotation.y=this.rng()*6;this.scene.add(rock);}
 // Distant skyline remains outside the traversable boundary.
 for(let i=0;i<18;i++){const x=-105+i*12,h=8+this.rng()*14;this.box(7+this.rng()*5,h,9,m.concrete,x,h/2,-118);}
 }
 addImportedProps(){const places=[['barrel',1.1,11,30],['pallet',.23,12,28],['trash',.6,-7,18],['trash',.45,-8,17],['barrier',.9,3,-43],['barrier',.9,-3,-45],['couch',.9,-38,25],['barrel',1.1,42,-58],['pallet',.25,44,-57],['trash',.55,30,12],['chest',.7,-61,-55]];for(const [key,height,x,z] of places){const prop=this.assets.create(key,{height,rotation:this.rng()*2});prop.position.set(x,0,z);this.scene.add(prop);if(key==='barrier'||key==='couch')this.solids.push({minX:x-1,maxX:x+1,minZ:z-.4,maxZ:z+.4,minY:0,maxY:height});}}
 makeGrass(){const template=this.assets.create('grass',{height:.5,rotation:0});template.updateMatrixWorld(true);const transforms=[],dummy=new THREE.Object3D();for(let i=0;i<2400;i++){const x=this.rng()*220-110,z=this.rng()*220-110;if((Math.abs(x)<4.3||Math.abs(z-24)<3.5||Math.abs(z+51)<3.5)&&this.rng()>.025)continue;if(this.buildings.some(b=>Math.abs(x-b.x)<b.w/2+.2&&Math.abs(z-b.z)<b.d/2+.2))continue;dummy.position.set(x,0,z);dummy.rotation.y=this.rng()*6.28;dummy.scale.setScalar(.65+this.rng()*.8);dummy.updateMatrix();transforms.push(dummy.matrix.clone());}this.grass=new THREE.Group();template.traverse(mesh=>{if(!mesh.isMesh)return;const geometry=mesh.geometry.clone().applyMatrix4(mesh.matrixWorld);const instances=new THREE.InstancedMesh(geometry,mesh.material,transforms.length);transforms.forEach((m,i)=>instances.setMatrixAt(i,m));instances.receiveShadow=true;instances.castShadow=false;instances.instanceMatrix.needsUpdate=true;this.grass.add(instances);});this.scene.add(this.grass);}
 organic(rx,ry,rz,mat,x,y,z,parent){const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,10,8),mat);mesh.scale.set(rx,ry,rz);mesh.position.set(x,y,z);mesh.castShadow=true;parent.add(mesh);return mesh;}
 makeDog(){return this.assets.create('dog',{height:.92,animate:true});}
 makeEnemy(x,z,animal=false){const key=animal?'dog':'zombie';const g=this.assets.create(key,{height:animal?.8:1.9,rotation:Math.PI,animate:true});g.position.set(x,0,z);Object.assign(g.userData,{health:animal?55:85,home:{x,z},state:'wander',timer:this.rng()*6,attackAt:0,animal,dead:false,respawn:0,lastSeen:null,searchUntil:0});this.scene.add(g);this.enemies.push(g);return g;}
 makeViewWeapon(){this.viewScene=new THREE.Scene();this.viewCamera=new THREE.PerspectiveCamera(65,this.camera.aspect,.02,5);this.viewScene.add(this.viewCamera);this.viewLight=new THREE.HemisphereLight('#f5efdf','#656a5a',2.8);this.viewScene.add(this.viewLight);const key=new THREE.DirectionalLight('#e9e5cc',1.8);key.position.set(-2,4,1);this.viewScene.add(key);this.viewModel=new ViewModel(this.viewCamera,this.assets);this.viewWeapon=this.viewModel.root;this.muzzle=new THREE.PointLight('#ffc565',0,4);this.camera.add(this.muzzle);this.muzzle.position.set(.2,-.18,-.8);}
 impact(point,direction=new THREE.Vector3(0,0,-1),heavy=false){const group=new THREE.Group();group.position.copy(point);for(let i=0;i<(heavy?15:10);i++){const mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(.015+Math.random()*.018,0),this.m.red);mesh.userData.velocity=new THREE.Vector3((Math.random()-.5)*1.6,.3+Math.random()*1.1,(Math.random()-.5)*1.6).addScaledVector(direction,-.65);group.add(mesh);}this.scene.add(group);this.effects.push({group,life:.38});}
 makeRain(){const a=new Float32Array(1800);for(let i=0;i<a.length;i+=3){a[i]=(this.rng()-.5)*45;a[i+1]=this.rng()*25;a[i+2]=(this.rng()-.5)*45;}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(a,3));this.rain=new THREE.Points(geo,new THREE.PointsMaterial({color:'#c6d2c2',size:.06,transparent:true,opacity:.45}));this.scene.add(this.rain);}
 collides(x,z,r=.32,y=0){if(Math.abs(x)>112||Math.abs(z)>112)return true;return this.solids.some(b=>b.minY<y+1.65&&b.maxY>y+.1&&x+r>b.minX&&x-r<b.maxX&&z+r>b.minZ&&z-r<b.maxZ);}
 move(obj,dx,dz,r=.32,y=0){if(!this.collides(obj.x+dx,obj.z,r,y))obj.x+=dx;if(!this.collides(obj.x,obj.z+dz,r,y))obj.z+=dz;}
 segmentClear(a,b,r=.3){const length=Math.hypot(b.x-a.x,b.z-a.z),steps=Math.ceil(length/.4);for(let i=1;i<=steps;i++){const t=i/steps;if(this.collides(a.x+(b.x-a.x)*t,a.z+(b.z-a.z)*t,r))return false;}return true;}
 findPath(from,to){const pass=(x,z)=>{const key=x+','+z;if(!this.walkableCache.has(key))this.walkableCache.set(key,!this.collides(x,z,.34));return this.walkableCache.get(key);};let tx=Math.round(to.x),tz=Math.round(to.z);if(!pass(tx,tz)){let best=Infinity;const centerX=tx,centerZ=tz;for(let x=centerX-3;x<=centerX+3;x++)for(let z=centerZ-3;z<=centerZ+3;z++){const score=Math.hypot(x-to.x,z-to.z)+Math.hypot(x-from.x,z-from.z)*.02;if(pass(x,z)&&score<best){best=score;tx=x;tz=z;}}if(!Number.isFinite(best))return [];}
 const start={x:Math.round(from.x),z:Math.round(from.z),g:0,parent:null};start.f=Math.abs(start.x-tx)+Math.abs(start.z-tz);const open=[start],cost=new Map([[start.x+','+start.z,0]]);let iterations=0;while(open.length&&iterations++<5000){let index=0;for(let i=1;i<open.length;i++)if(open[i].f<open[index].f)index=i;const node=open.splice(index,1)[0];if(node.x===tx&&node.z===tz){const result=[];for(let n=node;n.parent;n=n.parent)result.unshift({x:n.x,z:n.z});return result;}for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=node.x+dx,z=node.z+dz,key=x+','+z,g=node.g+1;if(!pass(x,z)||(cost.has(key)&&cost.get(key)<=g))continue;cost.set(key,g);open.push({x,z,g,f:g+Math.abs(x-tx)+Math.abs(z-tz),parent:node});}}return [];}
 navigate(object,target,dt,speed,r=.3){const p=object.position;let goal=target;const direct=this.segmentClear(p,target,r);if(!direct){const nav=object.userData.navigation;const changed=!nav||Math.hypot(nav.target.x-target.x,nav.target.z-target.z)>3;if((!nav||this.time>nav.next)&&(changed||!nav.path.length)){object.userData.navigation={target:{x:target.x,z:target.z},path:this.findPath(p,target),next:this.time+1.5};}const current=object.userData.navigation;if(current?.path.length){while(current.path.length&&Math.hypot(current.path[0].x-p.x,current.path[0].z-p.z)<.35)current.path.shift();goal=current.path[0]||target;}else return false;}else object.userData.navigation=null;const dx=goal.x-p.x,dz=goal.z-p.z,dist=Math.hypot(dx,dz);if(dist<.1)return false;const step=Math.min(dist,speed*dt);this.move(p,dx/dist*step,dz/dist*step,r);object.rotation.y=Math.atan2(-dx,-dz);return true;}
 visible(a,b){const from=new THREE.Vector3(a.x,a.y??1.5,a.z),to=new THREE.Vector3(b.x,b.y??1.5,b.z),delta=to.sub(from);const distance=delta.length();if(distance<.01)return true;const ray=new THREE.Raycaster(from,delta.normalize(),.05,distance-.15);return !ray.intersectObjects(this.raycastSolids,false).length;}
 syncCorpses(corpses){for(const [id,g] of this.corpseModels)if(!corpses.some(c=>c.id===id)){this.scene.remove(g);g.children.forEach(c=>c.geometry?.dispose());this.corpseModels.delete(id);this.interactables=this.interactables.filter(i=>i.id!==id);}for(const c of corpses){if(this.corpseModels.has(c.id))continue;const g=new THREE.Group();g.position.set(c.x,0,c.z);this.box(.6,.25,1.65,this.m.cloth,0,.16,0,g);this.box(.5,.45,.45,this.m.wood,.55,.24,.1,g);this.scene.add(g);this.corpseModels.set(c.id,g);this.addInteract('corpse','遗落的背包',c.x,.5,c.z,g,{id:c.id});}}
 updateVisual(s,dt,{menu=false,flashlight=false,moving=false,aim=false,recoil=0,jump=0,crouch=false,reloading=false,paused=false}={}){this.time+=dt;const day=Math.max(0,Math.sin((s.dayTime-6)/24*Math.PI*2));const storm=['暴雨','雾'].includes(s.weather);const sky=new THREE.Color().lerpColors(new THREE.Color('#111d23'),new THREE.Color(storm?'#78877a':'#9ca88d'),day);this.scene.background.copy(sky);this.scene.fog.color.copy(sky);this.scene.fog.density=s.weather==='雾'?.037:s.weather==='暴雨'?.023:.011;this.hemi.intensity=.4+day*(storm?1.35:2.2);this.sun.intensity=.1+day*(storm?.5:2.6);this.sun.position.set(s.position.x-35,20+day*65,s.position.z+25);this.sun.target.position.set(s.position.x,0,s.position.z);this.flashlight.intensity=flashlight&&s.flashlight>0?35:0;
 this.rain.visible=['小雨','暴雨'].includes(s.weather);if(this.rain.visible){this.rain.position.set(s.position.x,0,s.position.z);const a=this.rain.geometry.attributes.position.array;for(let i=1;i<a.length;i+=3){a[i]-=dt*18;if(a[i]<0)a[i]=25;}this.rain.geometry.attributes.position.needsUpdate=true;}
 if(menu){this.camera.position.set(1,2.4,30);this.camera.lookAt(-1,2,-12);this.camera.rotation.y+=Math.sin(this.time*.06)*.035;this.viewWeapon.visible=false;}else{this.camera.position.set(s.position.x,(crouch?1.12:1.72)+jump+(moving?Math.sin(this.time*10)*.035:0),s.position.z);const kick=this.hitKick||0;this.camera.rotation.set(s.pitch+recoil*.03+kick*.012,s.yaw,kick*.008,'YXZ');if(!paused)this.hitKick=kick*Math.exp(-22*dt);this.viewWeapon.visible=true;this.viewModel.update(paused?0:dt,{type:s.bag.find(i=>i.id===s.equipped)?.type,aim,recoil,moving,time:s.time,reloading});const targetFov=aim?49:72;this.camera.fov+=(targetFov-this.camera.fov)*Math.min(1,dt*12);this.camera.updateProjectionMatrix();}this.muzzle.intensity=Math.max(0,this.muzzle.intensity-dt*60);if(!paused){for(const actor of [this.dog,...this.enemies]){const u=actor.userData,held=Math.min(dt,u.hitFreeze||0);u.hitFreeze=Math.max(0,(u.hitFreeze||0)-dt);u.mixer?.update(dt-held);}for(const effect of [...this.effects]){effect.life-=dt;for(const mesh of effect.group.children){mesh.position.addScaledVector(mesh.userData.velocity,dt);mesh.userData.velocity.y-=dt*4;}if(effect.life<=0){this.scene.remove(effect.group);effect.group.children.forEach(n=>n.geometry.dispose());this.effects.splice(this.effects.indexOf(effect),1);}}}this.renderer.autoClear=true;this.renderer.render(this.scene,this.camera);if(!menu){this.viewCamera.aspect=this.camera.aspect;this.viewCamera.fov=aim?53:65;this.viewCamera.updateProjectionMatrix();this.viewLight.intensity=.8+day*2;this.renderer.autoClear=false;this.renderer.clearDepth();this.renderer.render(this.viewScene,this.viewCamera);this.renderer.autoClear=true;}}
}
