import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:(process.env.SOFTWARE_GL||process.platform!=='darwin')?['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']:['--enable-webgl','--use-angle=metal']});
const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>!!window.__survival,{},{timeout:60000});await page.waitForTimeout(1800);await page.screenshot({path:'artifacts/title.png'});
const inaccessible=await page.evaluate(()=>{const w=__survival.world;return w.interactables.filter(i=>i.type==='loot'&&i.id.indexOf('car-')!==0).filter(i=>{for(let a=0;a<16;a++){const angle=a/16*Math.PI*2,x=i.x+Math.sin(angle)*2,z=i.z+Math.cos(angle)*2;if(!w.collides(x,z,.32)&&w.visible({x,z,y:1.72},{x:i.x,z:i.z,y:i.y}))return false;}return true;}).map(i=>i.id);});assert.deepEqual(inaccessible,[],'loot containers have a reachable interaction angle');
console.log('scene',await page.evaluate(()=>({calls:__survival.world.renderer.info.render.calls,triangles:__survival.world.renderer.info.render.triangles,buildings:__survival.world.buildings.length,enemies:__survival.world.enemies.length})));
await page.click('#start');await page.waitForTimeout(700);assert.ok(await page.evaluate(()=>__survival.started));
// Real keyboard movement and inventory/map controls.
const before=await page.evaluate(()=>__survival.game.s.position.z);await page.keyboard.down('KeyW');await page.waitForTimeout(650);await page.keyboard.up('KeyW');const after=await page.evaluate(()=>__survival.game.s.position.z);assert.ok(after<before,'W moves player forward');
await page.keyboard.press('Tab');await page.waitForTimeout(250);assert.ok(await page.locator('#inventory').isVisible());await page.screenshot({path:'artifacts/inventory.png'});const paused=await page.evaluate(()=>__survival.game.s.time);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>__survival.game.s.time),paused,'inventory pauses simulation');await page.click('#inventory [data-close]');await page.waitForFunction(()=>document.pointerLockElement?.id==='world'&&__survival.locked&&!__survival.panel);await page.keyboard.press('KeyM');assert.ok(await page.locator('#map-panel').isVisible());await page.screenshot({path:'artifacts/map.png'});await page.click('#map-panel [data-close]');await page.waitForFunction(()=>document.pointerLockElement?.id==='world'&&__survival.locked&&!__survival.panel);
// Walk through an actual doorway, collide with the solid part of the wall.
await page.evaluate(()=>{const {game}=__survival;game.s.position={x:20,z:12.5};game.s.yaw=0;game.s.pitch=0;});await page.waitForTimeout(150);await page.keyboard.down('KeyW');await page.waitForFunction(()=>__survival.game.s.position.z<10.8,{},{timeout:10000});await page.keyboard.up('KeyW');assert.ok(await page.evaluate(()=>__survival.game.s.position.z<10.8),'doorway is enterable');
await page.evaluate(()=>{__survival.game.s.position={x:16,z:12.5};});await page.keyboard.down('KeyW');await page.waitForTimeout(1000);await page.keyboard.up('KeyW');assert.ok(await page.evaluate(()=>__survival.game.s.position.z>11.3),'wall blocks player');
// Use the real interaction key to open safe; transfer via rendered buttons.
await page.evaluate(()=>{const s=__survival.game.s;s.position={x:-10,z:47};s.yaw=0;s.pitch=-.35;});await page.waitForTimeout(350);console.log('interaction',await page.locator('#interaction').textContent());await page.keyboard.press('KeyE');await page.waitForTimeout(250);assert.ok(await page.locator('#inventory').isVisible(),'safe is interactable');assert.match(await page.locator('#container-title').textContent(),/保险柜/);await page.locator('#container-list .item-row').filter({hasText:'9mm 手枪'}).getByRole('button',{name:'取出'}).click();assert.ok(await page.evaluate(()=>__survival.game.s.bag.some(i=>i.type==='pistol')));await page.locator('#container-list .item-row').filter({hasText:'9mm 子弹'}).getByRole('button',{name:'取出'}).click();await page.click('#inventory [data-close]');await page.waitForFunction(()=>document.pointerLockElement?.id==='world'&&__survival.locked&&!__survival.panel);await page.keyboard.press('Digit2');await page.waitForFunction(()=>__survival.game.weapon?.type==='pistol');await page.keyboard.press('KeyR');await page.waitForFunction(()=>__survival.game.weapon.loaded===12,{},{timeout:10000});assert.equal(await page.evaluate(()=>__survival.game.weapon.loaded),12);
// Shoot a visible enemy, then verify a wall occludes shooting.
await page.evaluate(()=>{const {game,world}=__survival;game.s.position={x:0,z:20};game.s.yaw=0;game.s.pitch=-.10;const e=world.enemies[0];e.position.set(0,0,14);e.userData.health=85;e.userData.state='wander';e.userData.home={x:0,z:14};e.userData.timer=0;});await page.waitForFunction(()=>__survival.world.camera.position.z===20);await page.waitForTimeout(100);await page.mouse.down();await page.mouse.up();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>__survival.game.weapon.loaded),11);assert.ok(await page.evaluate(()=>__survival.world.enemies[0].userData.health<85),'bullet hits enemy');
await page.keyboard.press('KeyQ');await page.keyboard.press('KeyF');await page.evaluate(()=>{__survival.game.s.yaw=0;__survival.game.s.pitch=0;});await page.waitForTimeout(300);await page.screenshot({path:'artifacts/gameplay.png'});
// A building wall must stop a bullet even when an enemy stands behind it.
await page.evaluate(()=>{const {game,world}=__survival;game.s.position={x:16,z:13};game.s.yaw=0;game.s.pitch=-.06;const e=world.enemies[0];e.position.set(16,0,8);Object.assign(e.userData,{health:85,state:'wander',home:{x:16,z:8},timer:0});});await page.waitForFunction(()=>__survival.world.camera.position.z===13);await page.waitForTimeout(400);await page.mouse.down();await page.mouse.up();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>__survival.world.enemies[0].userData.health),85,'wall stops bullets');
const path=await page.evaluate(()=>{const w=__survival.world;const points=w.findPath({x:16,z:13},{x:16,z:7});return {length:points.length,valid:points.every(p=>!w.collides(p.x,p.z,.32)),door:points.some(p=>Math.abs(p.x-20)<1.3&&Math.abs(p.z-11)<1)};});assert.ok(path.valid&&path.door&&path.length>0,'AI routes through doorway');
// Put firearm back into safe and prove death/reload preserves it.
await page.evaluate(()=>{const g=__survival.game;const w=g.weapon;g.transfer(g.s.bag,g.s.safe,w.id,g.s.safeCapacity);g.damage(999);});await page.locator('#death').waitFor({state:'visible',timeout:10000});assert.ok(await page.locator('#death').isVisible());assert.ok(await page.evaluate(()=>__survival.game.s.corpses.length>0));assert.equal(await page.evaluate(()=>__survival.game.s.bag.length),0);await page.waitForTimeout(2300);await page.click('#respawn');await page.waitForTimeout(350);assert.ok(await page.evaluate(()=>__survival.game.s.safe.some(i=>i.type==='pistol')));assert.equal(await page.evaluate(()=>__survival.game.s.bag.some(i=>i.type==='pistol')),false);await page.evaluate(()=>__survival.save());await page.reload();await page.waitForFunction(()=>!!window.__survival);assert.ok(await page.evaluate(()=>__survival.game.s.safe.some(i=>i.type==='pistol')));assert.equal(await page.evaluate(()=>__survival.game.s.deaths),1);
assert.deepEqual(errors,[]);console.log('PASS: movement, collisions, doors, UI, pause, safe transfers, reload, shooting, dog command, flashlight, death, respawn, persistence.');} catch(error) {console.log('Browser errors:',errors);console.log('Failure state:',await page.evaluate(()=>window.__survival?{panel:__survival.panel,locked:!!document.pointerLockElement,time:__survival.game.s.time,keys:__survival.keys,position:__survival.game.s.position,yaw:__survival.game.s.yaw,camera:__survival.world.camera.position.toArray(),doorBlocked:__survival.world.collides(20,11,.32),reloadAt:__survival.game.reloadAt,weapon:__survival.game.weapon}:null));throw error;}finally{await browser.close();}
