import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--use-angle=metal']});
try{const page=await browser.newPage({viewport:{width:1200,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning')console.log(m.text())});await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.__survival,{},{timeout:60000});await page.click('#start');await page.keyboard.press('Escape');await page.evaluate(()=>{const {game,world}=__survival;document.querySelector('#pause').hidden=true;game.s.position={x:0,z:23};game.s.yaw=0;game.s.pitch=0;game.s.dayTime=12;game.s.weather='晴';world.enemies.forEach(e=>e.visible=false);const e=world.enemies.find(e=>!e.userData.animal);e.visible=true;e.position.set(-.3,0,20.7);e.rotation.set(0,Math.PI,0);world.dog.visible=false;world.assets.play(e,'Idle');e.userData.mixer.update(.5);window.subject=e;});await page.waitForTimeout(500);await page.screenshot({path:'artifacts/feedback-idle.png'});console.log(JSON.stringify(await page.evaluate(()=>{const {world}=__survival;return {clips:subject.userData.clips.map(c=>[c.name,c.tracks.length,c.duration]),hand:world.viewModel.bones.wristr.quaternion.toArray()};})));

await page.setViewportSize({width:669,height:930});await page.waitForTimeout(150);await page.screenshot({path:'artifacts/feedback-narrow.png'});await page.setViewportSize({width:1200,height:900});
// Every clip must drive the imported rig, including the final collapsed death pose.
for(const [name,seconds] of [['Walk',.45],['Run',.4],['Punch',.5],['Death',1.8]]){
 const result=await page.evaluate(([name,seconds])=>{const {world}=__survival;world.assets.play(subject,name,{once:name==='Death'});subject.userData.mixer.update(seconds);subject.updateMatrixWorld(true);const bones=[];subject.traverse(n=>{if(n.isBone)bones.push(n.quaternion.toArray())});return {clip:subject.userData.clipName,finite:bones.flat().every(Number.isFinite)};},[name,seconds]);assert.equal(result.clip,name);assert.ok(result.finite);await page.screenshot({path:'artifacts/feedback-zombie-'+name.toLowerCase()+'.png'});
}
await page.evaluate(()=>{const vm=__survival.world.viewModel;window.updateView=vm.update.bind(vm);vm.update=()=>{};vm.swing();subject.visible=false;});
for(const [name,dt] of [['windup',.10],['strike',.19],['recover',.2],['rest',.2]]){
 const grip=await page.evaluate(dt=>{const vm=__survival.world.viewModel;updateView(dt,{type:'crowbar',aim:false,recoil:0,moving:false,time:12,reloading:false});const wrist=vm.bones.wristr;const V=wrist.position.constructor;const expected=wrist.localToWorld(new V(-.25,.67,0)),actual=vm.weapon.getWorldPosition(new V());return {error:expected.distanceTo(actual),finite:Object.values(vm.bones).every(b=>b.quaternion.toArray().every(Number.isFinite)),remaining:vm.meleeTime};},dt);assert.ok(grip.error<1e-5,'bat stays fixed in the palm throughout swing');assert.ok(grip.finite);await page.screenshot({path:'artifacts/feedback-melee-'+name+'.png'});
}
// Exercise the real mouse path: wind-up precedes damage, and one swing hits once.
await page.evaluate(()=>{const {game,world}=__survival;world.viewModel.update=updateView;game.lastShot=-10;game.s.position={x:0,z:23};game.s.pitch=-.4;game.s.yaw=0;game.s.dog.health=10;world.dog.position.set(80,0,80);subject.visible=true;subject.position.set(0,0,21.2);Object.assign(subject.userData,{dead:false,health:85,state:'wander',home:{x:0,z:21.2},timer:0});subject.userData.mixer.stopAllAction();subject.userData.clipName=null;world.assets.play(subject,'Idle');subject.userData.mixer.update(.5);});
await page.keyboard.press('Escape');await page.waitForFunction(()=>__survival.locked&&!__survival.panel);await page.waitForFunction(()=>Math.abs(__survival.world.camera.rotation.x+.4)<.01);await page.mouse.down();await page.mouse.up();
assert.equal(await page.evaluate(()=>subject.userData.health),85,'wind-up does not deal immediate damage');await page.waitForFunction(()=>subject.userData.health<85);await page.waitForFunction(()=>__survival.world.viewModel.meleeTime===0);assert.equal(await page.evaluate(()=>subject.userData.health),55,'one swing deals one hit');
await page.evaluate(()=>{const {game}=__survival;const gun=game.s.safe.find(i=>i.type==='pistol');game.transfer(game.s.safe,game.s.bag,gun.id,game.s.capacity);game.s.equipped=gun.id;game.weapon.loaded=4;game.lastShot=-10;});await page.waitForFunction(()=>__survival.world.viewModel.type==='pistol');await page.keyboard.press('KeyV');await page.waitForFunction(()=>__survival.world.viewModel.type==='crowbar');assert.equal(await page.evaluate(()=>__survival.game.weapon.type),'pistol');await page.waitForFunction(()=>__survival.world.viewModel.type==='pistol');assert.equal(await page.evaluate(()=>__survival.game.weapon.loaded),4,'quick melee preserves gun ammo');
assert.deepEqual(errors,[]);console.log('PASS: zombie animation clips and stable palm attachment across the melee swing.');
}finally{await browser.close();}
